import { mkdir, rm, writeFile, copyFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';

const root = process.cwd();
const dist = join(root, 'dist');
const base = (process.env.SITE_BASE || '').replace(/\/$/, '');
const siteUrl = (process.env.SITE_URL || 'https://routerportals.xyz').replace(/\/$/, '');
const pageUrl = (path) => `${base}${path}`;
const canonical = (path) => `${siteUrl}${path}`;

const ipProfiles = [
  {ip:"192.168.0.1", brands:"D-Link, TP-Link ও কিছু Netgear model-এ দেখা যেতে পারে; exact model যাচাই জরুরি।", use:"অনেক home router-এর সম্ভাব্য local gateway ও admin address।", typos:"192.168.0.l, 192.168.o.1, 192.168.0.1., 19216801", queries:"192.168.0.1 login, 192.168.0.1 admin page, 192.168.0.1 not working, D-Link 192.168.0.1", special:"Addressটি common হলেও universal নয়; current Default Gateway-ই বেশি নির্ভরযোগ্য।"},
  {ip:"10.0.0.1", brands:"Xfinity gateway ও কিছু বিশেষ router/use-case-এ দেখা যায়; সব router-এর default নয়।", use:"10.0.0.0/8 private range-এর সম্ভাব্য local gateway বা admin address।", typos:"10.0.0.0.1, 10.0.0.01, 10.0.0.l, 10.0.o.1", queries:"10.0.0.1 router login, 10.0.0.1 admin panel, 10.0.0.1 not opening, Xfinity 10.0.0.1", special:"কাজ না করলে 192.168.x.x অনুমান না করে connected device-এর gateway দেখুন।"},
  {ip:"192.168.8.1", brands:"Huawei Mobile WiFi-এর সঙ্গে শক্তিশালী association আছে; অন্য hotspot model-এ আলাদা হতে পারে।", use:"কিছু 4G/5G hotspot বা mobile router-এর local management address।", typos:"192.168.8.l, 192.168.81, 19216881, 192.168.l.1", queries:"192.168.8.1 login, Huawei 192.168.8.1, 192.168.8.1 not opening, 192.168.8.1 WiFi password", special:"যে hotspot/router-এর settings খুলবেন তার Wi‑Fi-তে যুক্ত থাকতে হবে।"},
  {ip:"192.168.1.254", brands:"কিছু ISP gateway ও নির্দিষ্ট router model-এ দেখা যেতে পারে; IP দেখে brand নিশ্চিত করা যায় না।", use:"কিছু modem-router বা gateway-এর সম্ভাব্য LAN management address।", typos:"192.168.l.254, 192.168.1.25, 192.168.1.254., 1921681254", queries:"192.168.1.254 login, 192.168.1.254 admin, 192.168.1.254 not working, 192.168.1.254 gateway", special:"192.168.1.1 কাজ না করলেও এটি স্বয়ংক্রিয়ভাবে সঠিক হবে না—gateway যাচাই করুন।"},
  {ip:"192.168.100.1", brands:"কিছু cable modem/gateway, Motorola ও selected ISP equipment-এ দেখা যায়; model-specific।", use:"কিছু modem বা router-এর local administration address।", typos:"192.168.l00.1, 192.168.100.l, 192.168.10.1, 192.168.100.1.", queries:"192.168.100.1 login, modem 192.168.100.1, 192.168.100.1 admin, 192.168.100.1 not working", special:"কিছু network-এ এটি modem-side page, router-side gateway নয়।"},
  {ip:"192.168.2.1", brands:"Belkin-এর কিছু model-এ documented context আছে; অন্য brand-এ modelভেদে বদলায়।", use:"কিছু home router বা access point-এর সম্ভাব্য local admin address।", typos:"192.168.2.l, 19216821, 192-168-2-1, 192.168.2.1.com", queries:"192.168.2.1 login, Belkin 192.168.2.1, 192.168.2.1 admin, 192.168.2.1 not working", special:"Hyphenated form search result-এ দেখা গেলেও browser address bar-এ dotted IP ব্যবহার করুন।"},
  {ip:"192.168.10.1", brands:"WAVLINK ও কিছু selected router/access point-এ দেখা যেতে পারে; universal নয়।", use:"কিছু router, repeater বা access point-এর local setup page-এর সম্ভাব্য address।", typos:"192.168.l0.1, 192.168.10.l, 192168101, 192.168.10.", queries:"192.168.10.1 login, 192.168.10.1 router, 192.168.10.1 not opening, 192.168.10.1 password", special:"দুইটি zero বা letter l/o নিয়ে typo বেশি হয়; valid IPv4-তে শুধু digit ও dot থাকে।"},
  {ip:"192.168.11.1", brands:"কিছু Buffalo AirStation context-এ দেখা যায়; exact device manual ছাড়া নিশ্চিত নয়।", use:"কিছু router বা network device-এর local management address।", typos:"192.168.l.l, 192.168.11.l, 192168111, 192.168.11,1", queries:"192.168.11.1 login, Buffalo 192.168.11.1, 192.168.11.1 admin, 192.168.11.1 not working", special:"192.168.1.1 ও 192.168.11.1 আলাদা address; পুরো IP লিখুন।"},
  {ip:"192.168.0.254", brands:"কিছু TP-Link, D-Link, Netgear, Tenda বা Zyxel device-এ সম্ভাব্য; model verification প্রয়োজন।", use:"কিছু router, extender বা access point-এর সম্ভাব্য local gateway।", typos:"192.168.o.254, 192.168.0.25, 192 168 0 254, 192.168.0.254.com", queries:"192.168.0.254 login, 192.168.0.254 router, 192.168.0.254 admin, 192.168.0.254 not working", special:"এটি 192.168.0.0/16 private range-এর অংশ; একই address বহু network-এ থাকতে পারে।"},
  {ip:"192.168.31.1", brands:"Xiaomi router-এর সঙ্গে শক্তিশালী model context আছে; অন্য brand-এ অনুমান করা যাবে না।", use:"কিছু Xiaomi router-এর local setup বা management address।", typos:"192.168.l.l, 192.168.31.l, 192.168.3l.1, 192168311", queries:"192.168.31.1 login, Xiaomi 192.168.31.1, 192.168.31.1 setup, 192.168.31.1 not opening", special:"Xiaomi setup-এ একই network-এ যুক্ত থাকা জরুরি; এটি public Internet login নয়।"},
  {ip:"192.168.1.253", brands:"কিছু travel router বা managed network device-এ model-specific context আছে; universal brand mapping নয়।", use:"কিছু router, switch বা access point-এর সম্ভাব্য management address।", typos:"192.168.l.253, 192.168.1.25, 192.168.1.254, 192-168-1-253", queries:"192.168.1.253 login, 192.168.1.253 router, 192.168.1.253 admin, 192.168.1.253 not working", special:"কিছু device-এ management port বা VLAN আলাদা হতে পারে; current gateway যাচাই করুন।"}
];
function makeIpPage(x){
  const ip=x.ip, slug=ip.replaceAll('.', '-');
  return {slug:`/ip/${slug}/`, title:`${ip} Login: Router Admin Troubleshooting | Router Portal`, description:`Learn how to open ${ip} on your local router network, avoid common typos, find the correct gateway, and troubleshoot access safely.`, label:`${ip} router guide`, h1:`${ip} router login`, searchTerms:`${x.typos}, ${x.queries}`, intro:`${x.use} Use it only from the network that owns the device.`, body:`
    <div class="action-row"><a class="button" href="http://${ip}/">Open ${ip}</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my gateway</a><button class="button ghost" type="button" data-copy-ip="${ip}">Copy IP address</button></div>
    <div class="notice"><strong>Address context:</strong> ${x.special} This is a local/private address, not a public website.</div>
    <h2>What is ${ip} used for?</h2><p>${ip} may open a router, modem, extender, hotspot, switch, or gateway administration screen when your device is connected to the same Wi‑Fi or Ethernet network. The IP alone does not prove a brand, model, password, or ownership.</p>
    <h2>How to open the admin panel</h2><ol><li>Connect your phone or computer to the correct router Wi‑Fi or Ethernet network.</li><li>Open the browser <strong>address bar</strong>, not Google or another search box.</li><li>Type <strong>http://${ip}</strong> and press Enter using the exact dotted form.</li><li>At the login screen, use credentials printed on the device, supplied by the ISP, or previously set by the owner.</li><li>After login, change weak or old administrator credentials and save settings carefully.</li></ol>
    <h2>Brand and device context</h2><p>${x.brands} This is a context clue only. The current Default Gateway shown by your device is more reliable than a generic IP list.</p>
    <h2>Common typing mistakes</h2><p>People may search for <strong>${x.typos}</strong>. Letter <strong>l</strong> and number <strong>1</strong>, or letter <strong>o</strong> and number <strong>0</strong>, are often confused. Search engines may show results for a typo, but the router requires the correct local address.</p>
    <h2>If ${ip} does not open</h2><div class="checklist"><div class="check"><span class="step-no">1</span><div><strong>Confirm the network</strong><span>Stay connected to the router you are trying to manage. Turn off mobile data or another active Wi‑Fi while testing.</span></div></div><div class="check"><span class="step-no">2</span><div><strong>Find the actual gateway</strong><span>Use Windows <code>ipconfig</code>, macOS network details, Linux route information, or your phone’s connected Wi‑Fi details. The gateway may be different.</span></div></div><div class="check"><span class="step-no">3</span><div><strong>Test carefully</strong><span>Check power and cable/Wi‑Fi status, try another browser or Ethernet, and review VPN/proxy or extension interference.</span></div></div></div>
    <h2>Username and password safety</h2><div class="warning"><strong>No universal credential:</strong> Do not assume admin/admin, blank password, or any generic list is correct. Credentials vary by brand, model, firmware, ISP, and previous setup. Router Portal never receives or stores your password.</div>
    <h2>Before a factory reset</h2><p>A reset may erase the Wi‑Fi name, Wi‑Fi password, ISP settings, LAN IP, DHCP reservations, port rules, and security configuration. Treat reset as a last resort and follow exact model instructions. A normal reboot is not the same as a factory reset.</p>
    <h2>Related router help</h2><p><a href="${pageUrl('/router-login-not-working/')}">Router login troubleshooting</a>, <a href="${pageUrl('/forgot-router-password/')}">forgotten password help</a>, <a href="${pageUrl('/factory-reset-router/')}">factory reset warnings</a>, and <a href="${pageUrl('/find-router-ip/')}">find your router IP</a>.</p>
    <p><strong>Search intent covered:</strong> ${x.queries}. This page does not guarantee that every device uses ${ip}.</p>`};
}
const ipPages = ipProfiles.map(makeIpPage);

const brandProfiles = [
  {slug:"tp-link", name:"TP-Link", ips:"192.168.0.1, 192.168.1.1, tplinkwifi.net", models:"Archer C6, Archer C7, TL-WR841N", queries:"TP-Link router login, TP-Link admin password, 192.168.0.1 TP-Link, tplinkwifi.net login", match:"192.168.0.1"},
  {slug:"netgear", name:"NETGEAR", ips:"192.168.1.1, 192.168.0.1, routerlogin.net", models:"R7000, R6700, Nighthawk R8000", queries:"NETGEAR router login, routerlogin.net, NETGEAR admin password, 192.168.1.1 NETGEAR", match:"192.168.1.1"},
  {slug:"d-link", name:"D-Link", ips:"192.168.0.1, 192.168.1.1", models:"DIR-615, DIR-825", queries:"D-Link router login, D-Link admin password, 192.168.0.1 D-Link, DIR-615 login", match:"192.168.0.1"},
  {slug:"linksys", name:"Linksys", ips:"192.168.1.1, myrouter.local", models:"E1200, WRT54G", queries:"Linksys router login, Linksys admin password, 192.168.1.1 Linksys, myrouter.local", match:"192.168.1.1"},
  {slug:"tenda", name:"Tenda", ips:"192.168.0.1, tendawifi.com", models:"AC10, AC23", queries:"Tenda router login, Tenda admin password, 192.168.0.1 Tenda, tendawifi.com login", match:"192.168.0.1"},
  {slug:"huawei", name:"Huawei", ips:"192.168.8.1, 192.168.3.1", models:"B315, B535", queries:"Huawei router login, Huawei Mobile WiFi login, 192.168.8.1 Huawei, Huawei admin password", match:"192.168.8.1"},
  {slug:"asus", name:"ASUS", ips:"192.168.1.1, router.asus.com", models:"RT-AC68U, RT-AX series", queries:"ASUS router login, ASUS admin password, 192.168.1.1 ASUS, router.asus.com", match:"192.168.1.1"},
  {slug:"zte", name:"ZTE", ips:"192.168.1.1, 192.168.0.1", models:"4G/5G home routers, ISP gateways", queries:"ZTE router login, ZTE admin password, 192.168.1.1 ZTE, ZTE modem login", match:"192.168.1.1"},
  {slug:"belkin", name:"Belkin", ips:"192.168.2.1, 192.168.1.1", models:"N300, AC series", queries:"Belkin router login, Belkin admin password, 192.168.2.1 Belkin, Belkin setup", match:"192.168.2.1"},
  {slug:"arris", name:"ARRIS", ips:"192.168.0.1, 192.168.100.1", models:"SURFboard cable gateways", queries:"ARRIS router login, ARRIS modem login, 192.168.0.1 ARRIS, 192.168.100.1 ARRIS", match:"192.168.0.1"},
  {slug:"cisco", name:"Cisco", ips:"192.168.1.1, 192.168.0.1", models:"Linksys/Cisco home gateways, small-office devices", queries:"Cisco router login, Cisco admin password, 192.168.1.1 Cisco, Cisco gateway login", match:"192.168.1.1"},
  {slug:"xiaomi", name:"Xiaomi", ips:"192.168.31.1, miwifi.com", models:"Mi Router 4A, AX series", queries:"Xiaomi router login, Xiaomi admin password, 192.168.31.1 Xiaomi, miwifi.com login", match:"192.168.31.1"}
];
function makeBrandPage(x){
  const brand=x.name, slug=x.slug;
  const ipLinks=x.match.split(',').map(ip => `<a class="ip-chip" href="${pageUrl('/ip/'+ip.trim().replaceAll('.','-')+'/')}">${ip.trim()}</a>`).join(' ');
  return {slug:`/brand/${slug}/`, title:`${brand} Router Login: IP, Admin Password and Setup | Router Portal`, description:`Find ${brand} router login addresses, model context, admin password safety, Wi‑Fi settings and troubleshooting in one simple guide.`, label:`${brand} router guide`, h1:`${brand} router login`, searchTerms:`${x.queries}, ${x.ips}, ${x.models}`, intro:`A practical ${brand} router login guide with model-aware steps and safe credential guidance.`, body:`
    <div class="brand-hero-card"><div><span class="eyebrow">Brand login guide</span><h2>${brand} admin access</h2><p>Use the matching local address only while connected to your own ${brand} router or gateway.</p></div><div class="brand-mark">${brand.slice(0,2).toUpperCase()}</div></div>
    <div class="action-row"><a class="button" href="http://${x.match}/">Open ${x.match}</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my gateway</a><a class="button ghost" href="${pageUrl('/router-login-not-working/')}">Fix login problem</a></div>
    <div class="notice"><strong>Model check first:</strong> ${brand} login addresses, menu names and credentials can change by model, hardware revision, ISP firmware and previous setup. The brand name alone does not guarantee one IP or one password.</div>
    <h2>${brand} router login addresses</h2><p>Common possibilities for this brand include <strong>${x.ips}</strong>. Some models also use a local device name such as a setup hostname. If none opens, do not keep guessing: check the connected device's Default Gateway.</p><div class="brand-links">${ipLinks}</div>
    <h2>Simple login steps</h2><ol><li>Connect your phone or computer to the correct ${brand} router Wi‑Fi or Ethernet network.</li><li>Open the browser address bar, not Google search.</li><li>Enter the matching local IP or local setup address shown for your model.</li><li>Use the administrator credential printed on the label, supplied by your ISP, created during setup, or previously changed by the owner.</li><li>After login, change weak administrator credentials and save a recovery note somewhere private.</li></ol>
    <h2>Default username and password: what is safe to say?</h2><div class="warning"><strong>There is no universal ${brand} password.</strong> Some older or specific devices may show a username such as <strong>admin</strong>, a blank username, or a setup-created account; password examples can include a label-generated key or a model-specific default. These are examples only, not credentials to try blindly. Check the device label, manual, ISP setup sheet, or the exact model guide. Never send your password to Router Portal.</div>
    <h2>Popular model context</h2><div class="grid two-col"><div class="card"><span class="ip-chip">Model examples</span><p>${x.models}</p><a href="${pageUrl('/router-login/')}">Use the general login flow →</a></div><div class="card"><span class="ip-chip">Matching IP guide</span><p>${x.match} may be relevant to one or more ${brand} models, but confirm the current gateway.</p><a href="${pageUrl('/ip/'+x.match.replaceAll('.','-')+'/')}">Open IP guide →</a></div></div>
    <h2>${brand} Wi‑Fi and admin settings</h2><p>After a successful login, common tasks may include changing the Wi‑Fi name, changing the Wi‑Fi password, reviewing connected devices, updating firmware, checking guest access, and reviewing LAN/DHCP settings. Menu labels vary, so read each screen before saving.</p><div class="checklist"><div class="check"><span class="step-no">1</span><div><strong>Change Wi‑Fi safely</strong><span>Use a strong unique Wi‑Fi password and remember that changing it disconnects existing devices.</span></div></div><div class="check"><span class="step-no">2</span><div><strong>Protect the admin account</strong><span>Do not reuse the Wi‑Fi password as the administrator password when the router allows separate values.</span></div></div><div class="check"><span class="step-no">3</span><div><strong>Keep settings before reset</strong><span>A factory reset can erase ISP, LAN, Wi‑Fi, port and security settings.</span></div></div></div>
    <h2>${brand} login not working?</h2><p>Confirm the network, read the current Default Gateway, try Ethernet or another browser, review VPN/proxy interference, and check whether the ISP has changed the router firmware. A normal reboot is safer than a factory reset; reset only after reading the exact model instructions.</p>
    <h2>Related Router Portal pages</h2><p><a href="${pageUrl('/change-wifi-password/')}">Change Wi‑Fi password</a>, <a href="${pageUrl('/forgot-router-password/')}">forgot admin password</a>, <a href="${pageUrl('/factory-reset-router/')}">factory reset warning</a>, and <a href="${pageUrl('/router-login-not-working/')}">router login troubleshooting</a>.</p>
    <p><strong>Search intent covered:</strong> ${x.queries}.</p>`};
}
const brandPages = brandProfiles.map(makeBrandPage);

const pages = [
  {
    slug: '/',
    title: 'Router Login Help: IP, Admin Access and Troubleshooting | Router Portal',
    description: 'Simple router login help for 192.168.1.1, 192.168.0.1, 10.0.0.1, router IP discovery and common admin access problems.',
    label: 'A clearer way to reach your router',
    h1: 'Find your router login page',
    intro: 'Enter a router IP, brand, model, or problem and get a short, practical next step without the clutter.',
    home: true,
    body: `
      <section class="section"><div class="section-head"><div><span class="eyebrow">Start here</span><h2>Popular router login addresses</h2><p class="section-intro">Use these links only while connected to your own router or home network. They open a local address in your browser.</p></div></div><div class="grid">
        ${ipCard('192.168.1.1','Common router admin address — start with the login guide','/router-login/')}
        ${ipCard('192.168.0.1','Common router admin address — use the login guide','/router-login/')}
        ${ipCard('10.0.0.1','Common gateway address — find yours first','/find-router-ip/')}
        ${ipCard('192.168.8.1','Selected mobile routers — check your gateway','/find-router-ip/')}
        ${ipCard('Find your IP','Use your device settings','/find-router-ip/')}
        ${ipCard('Login problem','Fix an admin page that will not open','/router-login-not-working/')}
        ${ipPages.slice(0,6).map(p => ipCard(p.h1.replace(' router login',''), p.description, p.slug)).join('')}
      </div></section>
      <section class="section"><div class="section-head"><div><span class="eyebrow">Brand guides</span><h2>Find help by router brand</h2><p class="section-intro">Choose a brand for matching IP addresses, model context and safe admin-password guidance.</p></div></div><div class="grid brand-grid">${brandPages.map(p => ipCard(p.h1.replace(' router login',''), p.description, p.slug)).join('')}</div></section>
      <section class="section quick"><div class="section-head"><div><span class="eyebrow">Three quick steps</span><h2>Get to the right screen</h2></div></div><div class="quick-grid">
        <div class="quick-step"><span class="step-no">1</span><div><h3>Connect locally</h3><p>Join your router’s Wi-Fi or connect by Ethernet before opening a local IP.</p></div></div>
        <div class="quick-step"><span class="step-no">2</span><div><h3>Use the address bar</h3><p>Type the IP into your browser’s address bar, not into a search engine.</p></div></div>
        <div class="quick-step"><span class="step-no">3</span><div><h3>Try the next fix</h3><p>If the page does not open, check your gateway before resetting anything.</p></div></div>
      </div></section>
      <section class="section"><div class="notice"><strong>Local access reminder:</strong> Router Portal does not ask for your router password. A local admin address works only from the network that owns the router.</div></section>`
  },
  {
    slug: '/router-login/', title: 'How to Log In to Your Router | Router Portal', description: 'Learn how to open your router admin page, find the correct gateway, use the right credentials, and fix common router login problems safely.', label: 'Router admin access', h1: 'How to log in to your router', intro: 'Open your router control panel from your own local network. Router Portal never asks for or handles your password.', body: `
      <div class="answer-lead"><strong>Quick answer:</strong> Connect to your router’s Wi-Fi or Ethernet network, find its current Default Gateway, and type that local address into your browser’s address bar. Common examples include <strong>192.168.1.1</strong> and <strong>192.168.0.1</strong>, but your device’s gateway is the reliable answer.</div>
      <div class="action-row"><a class="button" href="http://192.168.1.1/">Open 192.168.1.1</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my router IP</a></div>
      <div class="notice"><strong>Before you start:</strong> Connect to the router you own or are authorised to manage. Type the address into the browser address bar—not into Google Search. A local admin page normally works only from that router’s network.</div>
      <h2>How to log in to your router</h2><ol><li>Connect your phone or computer to the correct router network by Wi-Fi or Ethernet.</li><li>Find the network’s <strong>Default Gateway</strong> if you do not know the router IP.</li><li>Open a browser and type the exact local address in the address bar, such as <strong>http://192.168.1.1</strong>.</li><li>Press Enter and use the username or password printed on the router label, supplied by your ISP, or created during setup.</li><li>After signing in, review security settings and replace weak or unchanged administrator credentials.</li></ol>
      <h2>Router admin password vs Wi-Fi password</h2><div class="grid two-col"><div class="card"><span class="ip-chip">Admin password</span><p>Opens the router’s settings panel. It may be printed on the device or created during setup.</p></div><div class="card"><span class="ip-chip">Wi-Fi password</span><p>Connects phones, computers, and other devices to the wireless network. It is not always the same as the admin password.</p></div></div>
      <h2>Try another common address</h2><div class="grid two-col"><div class="card"><span class="ip-chip">192.168.0.1</span><p>Common on some D-Link, TP-Link, and other home routers. Use it only while connected to the relevant network.</p><a href="${pageUrl('/ip/192-168-0-1/')}">Read the 192.168.0.1 guide →</a></div><div class="card"><span class="ip-chip">10.0.0.1</span><p>Used by some gateways and ISP equipment. Check the actual gateway instead of guessing repeatedly.</p><a href="${pageUrl('/ip/10-0-0-1/')}">Read the 10.0.0.1 guide →</a></div></div>
      <h2>Router login FAQ</h2><div class="faq-list"><details><summary>Why does 192.168.1.1 not open?</summary><p>Your router may use a different gateway, or your device may be on mobile data, another Wi-Fi network, or a guest network. <a href="${pageUrl('/find-router-ip/')}">Find the current gateway</a> first.</p></details><details><summary>Should I search for the IP in Google?</summary><p>No. Type the local address directly into the browser address bar. Searching for it can lead to unrelated results instead of your router’s local login screen.</p></details><details><summary>Is the router admin password the same as the Wi-Fi password?</summary><p>Not necessarily. The admin password opens settings; the Wi-Fi password joins the wireless network. Check the label or setup record for the correct credential.</p></details></div>
      <h2>Do not enter your password on this website</h2><p>Router Portal is an information site. It never receives, stores, or processes router credentials. Use only the login page served by your own router, and follow the relevant manufacturer or ISP instructions when a model-specific step is required.</p><div class="action-row"><a class="button ghost" href="${pageUrl('/router-login-not-working/')}">Login is not working</a><a class="button secondary" href="${pageUrl('/editorial-policy/')}">How we check information</a></div>`
  },
  {
    slug: '/find-router-ip/', title: 'Find Your Router IP Address and Default Gateway | Router Portal', description: 'Find the router IP or default gateway on Windows, macOS, Android, iPhone, iPad and Linux with simple steps.', label: 'Find the right local address', h1: 'How to find your router IP address', intro: 'The correct gateway shown by your device is more reliable than guessing a common IP.', body: `
      <h2>Windows</h2><ol><li>Open Command Prompt.</li><li>Run <code>ipconfig</code>.</li><li>Look for <strong>Default Gateway</strong> under the connected adapter.</li></ol><h2>macOS</h2><ol><li>Open System Settings and choose your connected network.</li><li>Open network details and look for Router.</li></ol><h2>Android and iPhone</h2><p>Open the details for the Wi-Fi network you are currently using. Look for Gateway, Router, or similar wording. The label varies by device and version.</p><h2>Linux</h2><p>Open a terminal and check the default route with your network tools. The address after <strong>default via</strong> is normally the gateway.</p><div class="warning"><strong>Important:</strong> The gateway may be different from the popular examples. Use the value shown for your current network.</div><div class="action-row"><a class="button" href="${pageUrl('/router-login/')}">Open the login guide</a><a class="button secondary" href="${pageUrl('/router-login-not-working/')}">Need another fix?</a></div>`
  },
  {
    slug: '/router-login-not-working/', title: 'Router Login Not Working: Fix the Admin Page | Router Portal', description: 'Fix a router login page that will not open. Check your connection, gateway, browser, and reset options step by step.', label: 'Troubleshooting', h1: 'Router login is not working', intro: 'Work through these checks in order before considering a factory reset.', body: `
      <div class="checklist"><div class="check"><span class="step-no">1</span><div><strong>Check the connection</strong><span>Make sure your device is connected to the router’s Wi-Fi or Ethernet network.</span></div></div><div class="check"><span class="step-no">2</span><div><strong>Check the address</strong><span>Use your device’s Default Gateway instead of guessing an IP.</span></div></div><div class="check"><span class="step-no">3</span><div><strong>Use the address bar</strong><span>Type the local address directly into the browser address bar.</span></div></div><div class="check"><span class="step-no">4</span><div><strong>Try another browser</strong><span>Disable a VPN temporarily and test a private window if appropriate.</span></div></div></div><h2>Still cannot open it?</h2><p>Restart the router and wait for it to finish starting. Check the label or setup information for the correct local address. A factory reset can erase your network settings, so do not use it as the first fix.</p><div class="warning"><strong>Reset warning:</strong> Only reset a router when you understand that the Wi-Fi name, password, ISP settings, and custom rules may be removed.</div><div class="action-row"><a class="button" href="${pageUrl('/find-router-ip/')}">Find the gateway</a><a class="button secondary" href="${pageUrl('/factory-reset-router/')}">Understand reset first</a></div>`
  },
  {
    slug: '/forgot-router-password/', title: 'Forgot Router Admin Password? Safe Recovery Steps | Router Portal', description: 'Forgot your router admin password? Learn the difference between admin and Wi-Fi passwords and the safest next steps.', label: 'Password recovery', h1: 'Forgot your router admin password?', intro: 'First identify which password you forgot. The admin password and Wi-Fi password are often different.', body: `
      <h2>Admin password or Wi-Fi password?</h2><p>The admin password opens the router settings page. The Wi-Fi password connects a device to the network. Changing one does not always change the other.</p><h2>Try the safe options first</h2><ol><li>Check the router label or setup record.</li><li>Ask the person who configured the router.</li><li>Use the router’s documented recovery flow if one exists.</li><li>Back up settings before making a change.</li></ol><div class="warning"><strong>Before resetting:</strong> A factory reset may erase ISP settings, Wi-Fi names, passwords, port rules, and parental controls.</div><h2>After a reset</h2><p>Reconnect using the setup instructions for your model, create a new strong admin password, and change the default Wi-Fi password.</p><div class="action-row"><a class="button" href="${pageUrl('/factory-reset-router/')}">Read reset warnings</a><a class="button secondary" href="${pageUrl('/router-login/')}">Return to login steps</a></div>`
  },
  {
    slug: '/change-wifi-password/', title: 'How to Change Your Wi-Fi Password Safely | Router Portal', description: 'Change your Wi-Fi password from a router admin page with a simple, safe checklist.', label: 'Wi-Fi settings', h1: 'Change your Wi-Fi password', intro: 'Use the router settings page on your own network, then reconnect your devices with the new password.', body: `
      <h2>General steps</h2><ol><li>Connect to your router network.</li><li>Open the router admin page using its local IP.</li><li>Sign in with the router’s admin credentials.</li><li>Open Wireless, Wi-Fi, WLAN, or Security settings.</li><li>Choose a strong new password and save.</li><li>Reconnect phones, computers, TVs, and other devices.</li></ol><h2>Choose a safer password</h2><p>Use a long, unique password that is not your name, address, phone number, or router brand. Do not reuse a sensitive account password.</p><div class="notice"><strong>Connection note:</strong> Saving wireless settings may disconnect the device briefly. Reconnect using the new password.</div><div class="action-row"><a class="button" href="${pageUrl('/router-login/')}">Open login steps</a><a class="button secondary" href="${pageUrl('/router-login-not-working/')}">Need login help?</a></div>`
  },
  {
    slug: '/factory-reset-router/', title: 'How to Factory Reset a Router: Warnings and Next Steps | Router Portal', description: 'Understand what a router factory reset removes, when to use it, and what to prepare before pressing reset.', label: 'Use with care', h1: 'Factory reset a router carefully', intro: 'A factory reset is a last-resort action that can remove your network configuration.', body: `
      <div class="warning"><strong>Do not reset first.</strong> A reset can erase your Wi-Fi name, Wi-Fi password, ISP configuration, admin password, port forwarding, and custom rules.</div><h2>Before pressing reset</h2><ul><li>Find the model and setup information.</li><li>Record settings you will need again.</li><li>Check whether a simple restart or gateway correction solves the problem.</li><li>Make sure you know how to set up the connection afterward.</li></ul><h2>General reset process</h2><ol><li>Keep the router powered on.</li><li>Use the reset control specified for your model.</li><li>Hold it only for the documented duration.</li><li>Wait for the router to restart fully.</li><li>Run the initial setup and create new passwords.</li></ol><p>The exact reset method differs by model. Do not use a random timing rule when you are unsure.</p><div class="action-row"><a class="button secondary" href="${pageUrl('/router-login-not-working/')}">Try login fixes first</a><a class="button" href="${pageUrl('/find-router-ip/')}">Find the gateway</a></div>`
  },
  {
    slug: '/ip/192-168-1-1/', title: '192.168.1.1 Login: Router Admin Troubleshooting | Router Portal', description: 'Open 192.168.1.1 router admin login, avoid 192.168.l.l typos, find your gateway, and fix common access problems.', label: 'Most searched router IP', h1: '192.168.1.1 router login', intro: 'Use this local address from your own router network. Type it into the browser address bar, not a search engine.', body: `
      <div class="action-row"><a class="button" href="http://192.168.1.1/">Open 192.168.1.1</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my gateway</a></div><div class="notice"><strong>Correct address:</strong> <span class="ip-large">192.168.1.1</span>. Common typing mistakes include 192.168.l.l, 192.168.1.1. and 19216811.</div><h2>How to log in</h2><ol><li>Connect your device to the router’s Wi-Fi or Ethernet network.</li><li>Type <strong>192.168.1.1</strong> in the browser address bar.</li><li>Press Enter and wait for the router login screen.</li><li>Use the credentials printed on your router label or setup information.</li><li>After signing in, change the default admin password if the router still uses one.</li></ol><h2>If 192.168.1.1 does not open</h2><ul><li>Confirm that your device is connected to the correct router.</li><li>Find the Default Gateway shown by your device instead of guessing.</li><li>Temporarily check VPN or browser issues.</li><li>Do not factory-reset the router as the first step.</li></ul><div class="warning"><strong>Credential safety:</strong> Router Portal never asks for or stores your router username or password. Default credentials vary by model and firmware.</div><h2>Private address, not a public website</h2><p>192.168.1.1 is normally a local network address. It works only when your device can reach the router that uses it. If your gateway is different, use the address shown by your device.</p><div class="action-row"><a class="button ghost" href="${pageUrl('/router-login-not-working/')}">Login is not working</a><a class="button secondary" href="${pageUrl('/factory-reset-router/')}">Read reset warning</a></div>`
  },
  {
    slug: '/about/', title: 'About Router Portal: Simple Router Login Help | Router Portal', description: 'Learn what Router Portal does, who it helps, and how the site explains router IP addresses and admin access.', label: 'About Router Portal', h1: 'Clear router help for everyday networks', intro: 'Router Portal explains local router access in simple language without asking for your admin credentials.', body: `
      <h2>What Router Portal is</h2><p>Router Portal is an independent information website about router login addresses, local network access, gateway discovery, Wi-Fi settings, and common router problems.</p><h2>Who it is for</h2><p>The guides are written for people who need a clear next step, whether they are trying to open a router admin panel, find a gateway, change a Wi-Fi password, or understand why a local address does not open.</p><h2>What we do not do</h2><ul><li>We do not log in to your router.</li><li>We do not collect your router username or password.</li><li>We do not claim to be a router manufacturer, ISP, or brand support service.</li><li>We do not promise that one IP address works for every model or network.</li></ul><div class="notice"><strong>Use the guide safely:</strong> Follow local-network instructions only for a router you own or are authorised to manage.</div><h2>How this site improves</h2><p>Pages are added gradually so that the wording, links, safety notes, and technical details can be reviewed before a new guide is published.</p>`
  },
  {
    slug: '/contact/', title: 'Contact Router Portal for Corrections and Updates | Router Portal', description: 'Learn how to suggest a correction or update for a Router Portal page without sharing router credentials or private network data.', label: 'Corrections and updates', h1: 'Help us keep router guides accurate', intro: 'Found a mistake or an outdated router detail? Prepare the page URL and a clear correction without sharing private credentials.', body: `
      <h2>What to include in a correction</h2><ol><li>The exact Router Portal page URL.</li><li>The sentence or step that appears incorrect.</li><li>A short explanation of the correction.</li><li>The router brand and model only when it is relevant.</li></ol><h2>Never include</h2><div class="warning"><strong>Do not send private access information.</strong> Never include a router username, password, Wi-Fi password, public IP, MAC address, serial number, account number, or screenshot containing private network data.</div><h2>Current contact process</h2><p>This first release does not include a login-protected contact form or a system that stores messages. Correction requests should be prepared with the information above and shared through the project owner’s designated contact channel when one is provided.</p><h2>What happens next</h2><p>A correction is reviewed against the page purpose and the relevant router or network context. A change may be made when the information is clear and verifiable; not every suggestion will be accepted as a universal rule.</p>`
  },
  {
    slug: '/editorial-policy/', title: 'Router Portal Editorial Policy and Review Process | Router Portal', description: 'Read Router Portal’s editorial rules for accuracy, clarity, safety warnings, updates, and corrections.', label: 'Editorial standards', h1: 'How Router Portal pages are reviewed', intro: 'Our editorial process prioritises useful steps, clear caveats, and safe local-router guidance over keyword repetition.', body: `
      <h2>Our editorial priorities</h2><ol><li>Answer the user’s immediate question early.</li><li>Use plain language before technical terminology.</li><li>Separate a common example from a guaranteed rule.</li><li>Warn before destructive actions such as factory reset.</li><li>Never ask a visitor to submit router credentials.</li></ol><h2>Research and verification</h2><p>Router Portal content is prepared by comparing the user problem, router and network terminology, device instructions, manufacturer context, and existing help patterns. Competitor pages may help identify user needs and gaps, but their wording, screenshots, tables, and layout are not copied.</p><h2>Updates and corrections</h2><p>Router details can differ by model, firmware, region, and ISP. Pages may be updated when a fact changes, a safer instruction becomes available, or a correction is supported by clear evidence. Pages may include a review note as the content system expands.</p><h2>Use of assistance tools</h2><p>Writing and code assistance may be used during preparation, but pages are reviewed for accuracy, safety, duplicate wording, broken links, and misleading universal claims before publication.</p><h2>Independence</h2><p>Router Portal is not an official manufacturer or internet-provider support channel and should not be mistaken for one.</p>`
  },
  {
    slug: '/information-policy/', title: 'Router Portal Information Policy: Accuracy and Updates | Router Portal', description: 'Understand how Router Portal organises router IP, admin login, troubleshooting, and network information for readers.', label: 'Information policy', h1: 'Information that is clear about its limits', intro: 'Router and network instructions are useful only when their limits are explained. Router Portal separates common examples from model-specific facts.', body: `
      <h2>Common information versus model-specific information</h2><p>Addresses such as 192.168.1.1 are common examples, not a guarantee for every router. A device’s current Default Gateway is often more reliable than guessing from a popular list.</p><h2>Credential information</h2><p>Router Portal does not present a universal username and password as guaranteed. Credentials can vary by model, firmware, setup process, and whether someone changed the default.</p><h2>Safety boundaries</h2><ul><li>Local admin links should be opened only while connected to the relevant network.</li><li>Do not enter router credentials into Router Portal.</li><li>Do not factory-reset before understanding what settings will be removed.</li><li>Do not apply a model-specific instruction to a different model without checking the context.</li></ul><h2>How we handle uncertainty</h2><p>When a detail cannot safely be stated as universal, the page says so and points the reader toward finding the current gateway, checking the device label, or using the model context. Unknown information is not filled with invented certainty.</p><h2>Page improvement</h2><p>New pages and revisions are added in small groups so that metadata, internal links, content quality, and safety wording can be checked together.</p>`
  },
  {
    slug: '/privacy/', title: 'Router Portal Privacy Notice and Data Safety | Router Portal', description: 'Read how Router Portal handles privacy, router credentials, local network information, and visitor data in this static website.', label: 'Privacy', h1: 'Your router credentials stay with you', intro: 'Router Portal is designed to provide information without asking for router passwords or private network details.', body: `
      <h2>Information we do not request</h2><ul><li>Router admin username or password.</li><li>Wi-Fi password or security key.</li><li>Public IP, MAC address, serial number, or ISP account details.</li><li>Private network screenshots containing sensitive information.</li></ul><h2>Static website design</h2><p>The first release is a static information site. It has no visitor account, no router login system, and no form that sends router credentials to us.</p><h2>Local links</h2><p>Buttons such as “Open 192.168.1.1” point to a local address in the visitor’s browser. Router Portal does not receive the router admin page or its password.</p><h2>Technical hosting data</h2><p>Like most public websites, the hosting and delivery platform may process technical request information needed to deliver pages, protect the service, and maintain reliability. Router Portal does not intentionally use the site to collect router secrets.</p><h2>Changes to this notice</h2><p>This notice may be updated when the site adds a feature that changes data handling. Any new form, analytics, or tool will be reviewed before it is added.</p>`
  },
  {
    slug: '/terms/', title: 'Router Portal Terms of Use and Safety Disclaimer | Router Portal', description: 'Read the Router Portal terms of use, local-router safety disclaimer, accuracy limits, and responsible access rules.', label: 'Terms of use', h1: 'Use Router Portal responsibly', intro: 'Router Portal provides general information. You are responsible for confirming that an instruction fits your own router, network, and permission level.', body: `
      <h2>Informational use</h2><p>Router Portal pages are general educational and troubleshooting information. They are not a guarantee that a specific IP, credential, setting, or reset process applies to every router.</p><h2>Authorised access only</h2><p>Use local admin instructions only for a router and network you own or are authorised to manage. Do not use the guides to access someone else’s network.</p><h2>Before changing settings</h2><ul><li>Confirm the router model and current network.</li><li>Keep setup information available.</li><li>Understand what a change or reset may remove.</li><li>Do not share passwords or private network identifiers with this site.</li></ul><h2>Accuracy limits</h2><p>Router interfaces and instructions can change with model, firmware, region, and provider configuration. When a page says an address is common, it does not mean that address is guaranteed for your device.</p><h2>External destinations</h2><p>A local-router button may open an address on your own network. Router Portal does not control that router interface or its content.</p><h2>Acceptance</h2><p>By using the website, you agree to use the information lawfully, safely, and with appropriate permission.</p>`
  }
  ,...ipPages
  ,...brandPages
];

function ipCard(label, text, href){ return `<div class="card"><span class="ip-chip">${label}</span><p>${text}</p><a href="${pageUrl(href)}">View the guide →</a></div>`; }
function escapeHtml(value){ return value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function header(){ return `<header class="site-header"><nav class="nav" aria-label="Primary navigation"><a class="brand" href="${pageUrl('/')}" aria-label="Router Portal home"><img src="${pageUrl('/assets/logo.svg')}" alt="Router Portal" width="172" height="50"></a><button class="nav-toggle" aria-expanded="false" aria-controls="primary-links">Menu</button><div id="primary-links" class="nav-links"><a href="${pageUrl('/router-login/')}">Router Login</a><a href="${pageUrl('/ip/192-168-1-1/')}">192.168.1.1</a><a href="${pageUrl('/find-router-ip/')}">Find IP</a><a href="${pageUrl('/brand/tp-link/')}">Brands</a><a href="${pageUrl('/router-login-not-working/')}">Login Help</a></div></nav></header>`; }
function footer(){ return `<footer class="site-footer"><div class="footer-inner"><div><a class="brand" href="${pageUrl('/')}" aria-label="Router Portal home"><img src="${pageUrl('/assets/logo.svg')}" alt="Router Portal" width="172" height="50"></a><p>Simple, safety-first help for router IP addresses, admin access, and home-network problems.</p></div><div><strong>Start here</strong><p><a href="${pageUrl('/router-login/')}">Router login</a><br><a href="${pageUrl('/find-router-ip/')}">Find router IP</a><br><a href="${pageUrl('/router-login-not-working/')}">Login troubleshooting</a><br><a href="${pageUrl('/ip/192-168-1-1/')}">192.168.1.1 guide</a></p></div><div><strong>About and policies</strong><p><a href="${pageUrl('/about/')}">About</a> · <a href="${pageUrl('/contact/')}">Corrections</a><br><a href="${pageUrl('/editorial-policy/')}">Editorial policy</a><br><a href="${pageUrl('/information-policy/')}">Information policy</a><br><a href="${pageUrl('/privacy/')}">Privacy</a> · <a href="${pageUrl('/terms/')}">Terms</a></p></div></div></footer>`; }
function searchBox(){ return `<div class="search-wrap"><form class="search-shell" id="site-search"><label class="sr-only" for="search-input">Search router help</label><input id="search-input" autocomplete="off" placeholder="Try 192.168.1.1 or router login problem"><button class="button" type="submit">Search</button></form><div id="search-results" class="search-results" aria-live="polite"></div></div>`; }
function layout(page){
  const hero = page.home ? `<section class="hero"><div class="hero-inner"><div><span class="eyebrow">${page.label}</span><h1>${page.h1}</h1><p>${page.intro}</p>${searchBox()}</div><div class="hero-art" aria-label="Illustration of a router connecting devices"><div class="network-card"><div class="router">LOCAL ROUTER</div><div class="nodes"><span class="node">⌂</span><span class="node">◎</span><span class="node">▣</span></div><div class="signal"></div><div style="text-align:center;color:#60708c;font-size:.9rem">Private network • clear next step</div></div></div></div></section>` : `<section class="page-hero"><div class="page-hero-inner"><div class="breadcrumbs"><a href="${pageUrl('/')}">Home</a> / Router help</div><span class="eyebrow">${page.label}</span><h1>${page.h1}</h1><p>${page.intro}</p></div></section>`;
  const main = page.home ? page.body : `<main class="content-layout"><article class="prose">${page.body}</article><aside class="side-card"><h3>Quick actions</h3><ul><li><a href="http://192.168.1.1/">Open 192.168.1.1</a></li><li><a href="${pageUrl('/find-router-ip/')}">Find your router IP</a></li><li><a href="${pageUrl('/router-login-not-working/')}">Fix login problems</a></li><li><a href="${pageUrl('/factory-reset-router/')}">Read reset warning</a></li></ul></aside></main>`;
  const isNoindex = page.noindex === true;
  const canonicalTag = isNoindex ? '' : `<link rel="canonical" href="${canonical(page.slug)}">`;
  const robotsTag = `<meta name="robots" content="${isNoindex ? 'noindex,follow' : 'index,follow'}">`;
  const socialTags = isNoindex ? '' : `<meta property="og:site_name" content="Router Portal"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:url" content="${canonical(page.slug)}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${page.title}"><meta name="twitter:description" content="${page.description}">`;
  const schema = isNoindex ? '' : (() => { const data = { '@context':'https://schema.org','@type':page.home?'WebSite':'WebPage',name:page.home?'Router Portal':page.title,url:canonical(page.slug),description:page.description }; if (page.home) data.publisher = { '@type':'Organization',name:'Router Portal',url:siteUrl,logo:{ '@type':'ImageObject',url:canonical('/assets/logo.svg') } }; return `<script type="application/ld+json">${JSON.stringify(data)}</script>`; })();
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${page.title}</title><meta name="description" content="${page.description}"><meta name="theme-color" content="#2f6fed"><meta name="google-site-verification" content="iah_huluCmfWfZhIDsoW2YW1HP9HJmICG1rkl1VXRqk">${robotsTag}${canonicalTag}<link rel="icon" href="${pageUrl('/assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${pageUrl('/assets/style.css')}">${socialTags}${schema}</head><body><a class="skip-link" href="#main">Skip to content</a>${header()}${hero}<div id="main">${main}</div>${footer()}<script src="${pageUrl('/assets/app.js')}" defer></script></body></html>`;
}

await rm(dist, { recursive: true, force: true });
await mkdir(join(dist, 'assets'), { recursive: true });
await mkdir(join(dist, 'assets'), { recursive: true });
for (const asset of ['style.css','logo.svg','favicon.svg']) await copyFile(join(root,'public/assets',asset), join(dist,'assets',asset));
const searchIndex = pages.map(p => ({ title:p.h1, description:p.description, path:pageUrl(p.slug), keywords:[p.h1, p.label, p.searchTerms || '', p.slug.replaceAll('/',' ').replaceAll('-',' ')] }));
const appJs = `(() => {
  const toggle = document.querySelector('.nav-toggle');
  const links = document.querySelector('.nav-links');
  if (toggle && links) {
    toggle.addEventListener('click', () => {
      const open = links.classList.toggle('open');
      toggle.setAttribute('aria-expanded', String(open));
    });
  }
  document.querySelectorAll('[data-copy-ip]').forEach(btn => btn.addEventListener('click', async () => { try { await navigator.clipboard.writeText(btn.dataset.copyIp); const old = btn.textContent; btn.textContent = 'Copied'; setTimeout(() => btn.textContent = old, 1200); } catch { btn.textContent = 'Copy manually'; } }));
    const form = document.querySelector('#site-search');
  const input = document.querySelector('#search-input');
  const results = document.querySelector('#search-results');
  if (form && input && results) {
    let index = [];
    fetch('${pageUrl('/search-index.json')}').then(r => r.json()).then(x => { index = x; }).catch(() => {});
    const show = () => {
      const q = input.value.trim().toLowerCase();
      if (!q) { results.style.display = 'none'; results.innerHTML = ''; return; }
      const hits = index.filter(item => (item.title + ' ' + item.description + ' ' + item.keywords.join(' ')).toLowerCase().includes(q)).slice(0, 6);
      results.innerHTML = hits.length ? hits.map(x => '<a href="' + x.path + '"><strong>' + x.title + '</strong><small>' + x.description + '</small></a>').join('') : '<div style="padding:14px;color:#60708c">No matching guide yet. Try a common router IP.</div>';
      results.style.display = 'block';
    };
    input.addEventListener('input', show);
    form.addEventListener('submit', e => { e.preventDefault(); const first = results.querySelector('a'); if (first) location.href = first.href; else show(); });
  }
})();`;
await writeFile(join(dist, 'assets/app.js'), appJs);
await writeFile(join(dist, 'search-index.json'), JSON.stringify(searchIndex, null, 2));
for (const page of pages) { const file = page.slug === '/' ? join(dist,'index.html') : join(dist,page.slug.replace(/^\//,'') ,'index.html'); await mkdir(dirname(file), {recursive:true}); await writeFile(file, layout(page)); }
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p=>`  <url><loc>${canonical(p.slug)}</loc></url>`).join('\n')}\n</urlset>\n`;
  await writeFile(join(dist,'sitemap.xml'), sitemap);
  await writeFile(join(dist,'sitemap.txt'), `${pages.map(p=>canonical(p.slug)).join('\n')}\n`);
  await writeFile(join(dist,'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${canonical('/sitemap.xml')}\nSitemap: ${canonical('/sitemap.txt')}\n`);
  await writeFile(join(dist,'manus-routes.json'), JSON.stringify({routes:pages.map(p=>({path:pageUrl(p.slug),title:p.h1}))}, null, 2));
  await writeFile(join(dist,'404.html'), layout({slug:'/404.html',noindex:true,title:'Page Not Found | Router Portal',description:'The router guide page could not be found.',label:'Not found',h1:'That page is not here',intro:'Try a popular router login guide instead.',body:`<main class="content-layout"><article class="prose"><h2>Try a common guide</h2><p><a href="${pageUrl('/router-login/')}">Router admin login</a> or <a href="${pageUrl('/find-router-ip/')}">find your router IP</a>.</p></article></main>`}));
console.log(`Built ${pages.length} pages at ${dist}`);
