import { mkdir, rm, writeFile, copyFile, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { makeRecommendedPages } from './recommended-pages.mjs';
import { makeFiftyPages } from './fifty-pages.mjs';
import { makeNewPages } from './new-pages.mjs';
import { makeModelPages } from './model-pages.mjs';
import { makeVersionTwoPages } from './version-two-pages.mjs';
import { makeAdditionalIpPages } from './additional-ip-pages.mjs';
import { makeIpPages50 } from './ip-pages-50.mjs';
import { makeIpPages100 } from './ip-pages-100.mjs';
import { makeIpPages200 } from './ip-pages-200.mjs';

const root = process.cwd();
const dist = join(root, 'dist');
const base = (process.env.SITE_BASE || '').replace(/\/$/, '');
const siteUrl = (process.env.SITE_URL || 'https://routerportals.xyz').replace(/\/$/, '');
const pageUrl = (path) => `${base}${path}`;
const canonical = (path) => `${siteUrl}${path}`;

const ipProfiles = [
  {ip:"192.168.0.1", brands:"Can be seen on D-Link, TP-Link and some Netgear models; Exact model verification is essential.", use:"Many home routers have a possible local gateway and admin address.", typos:"192.168.0.l, 192.168.o.1, 192.168.0.1., 19216801", queries:"192.168.0.1 login, 192.168.0.1 admin page, 192.168.0.1 not working, D-Link 192.168.0.1", special:"Address is common but not universal; Current Default Gateway is more reliable."},
  {ip:"10.0.0.1", brands:"Seen in Xfinity gateways and some special routers/use-cases; Not all routers default.", use:"Possible local gateway or admin address of 10.0.0.0/8 private range.", typos:"10.0.0.0.1, 10.0.0.01, 10.0.0.l, 10.0.o.1", queries:"10.0.0.1 router login, 10.0.0.1 admin panel, 10.0.0.1 not opening, Xfinity 10.0.0.1", special:"If that doesn’t work, look at the connected device’s gateway instead of assuming 192.168.x.x."},
  {ip:"192.168.8.1", brands:"Has strong association with Huawei Mobile WiFi; May differ in other hotspot models.", use:"Local management address of some 4G/5G hotspot or mobile router.", typos:"192.168.8.l, 192.168.81, 19216881, 192.168.l.1", queries:"192.168.8.1 login, Huawei 192.168.8.1, 192.168.8.1 not opening, 192.168.8.1 WiFi password", special:"The hotspot/router that opens its settings must be connected to Wi‑Fi."},
  {ip:"192.168.1.254", brands:"May appear on some ISP gateways and certain router models; Brand cannot be confirmed by IP.", use:"Possible LAN management address of some modem-router or gateway.", typos:"192.168.l.254, 192.168.1.25, 192.168.1.254., 1921681254", queries:"192.168.1.254 login, 192.168.1.254 admin, 192.168.1.254 not working, 192.168.1.254 gateway", special:"192.168.1.1 won’t work automatically—check the gateway."},
  {ip:"192.168.100.1", brands:"Found on some cable modems/gateways, Motorola and selected ISP equipment; model-specific.", use:"Local administration address of some modem or router.", typos:"192.168.l00.1, 192.168.100.l, 192.168.10.1, 192.168.100.1.", queries:"192.168.100.1 login, modem 192.168.100.1, 192.168.100.1 admin, 192.168.100.1 not working", special:"On some networks this is the modem-side page, not the router-side gateway."},
  {ip:"192.168.2.1", brands:"Some Belkin models have documented context; Varies by model in other brands.", use:"Possible local admin address of some home router or access point.", typos:"192.168.2.l, 19216821, 192-168-2-1, 192.168.2.1.com", queries:"192.168.2.1 login, Belkin 192.168.2.1, 192.168.2.1 admin, 192.168.2.1 not working", special:"Use the dotted IP in the browser address bar even if it appears in hyphenated form search results."},
  {ip:"192.168.10.1", brands:"WAVLINK can also be viewed on some selected routers/access points; Not universal.", use:"A possible address for the local setup page of some routers, repeaters or access points.", typos:"192.168.l0.1, 192.168.10.l, 192168101, 192.168.10.", queries:"192.168.10.1 login, 192.168.10.1 router, 192.168.10.1 not opening, 192.168.10.1 password", special:"Typo is more with two zero or letter l/o; valid IPv4 contains only digits and dots."},
  {ip:"192.168.11.1", brands:"Seen in some Buffalo AirStation context; Not sure without exact device manual.", use:"The local management address of some routers or network devices.", typos:"192.168.l.l, 192.168.11.l, 192168111, 192.168.11,1", queries:"192.168.11.1 login, Buffalo 192.168.11.1, 192.168.11.1 admin, 192.168.11.1 not working", special:"192.168.1.1 and 192.168.11.1 are different addresses; Enter the full IP."},
  {ip:"192.168.0.254", brands:"Possible on some TP-Link, D-Link, Netgear, Tenda or Zyxel devices; Model verification is required.", use:"Possible local gateway of some router, extender or access point.", typos:"192.168.o.254, 192.168.0.25, 192 168 0 254, 192.168.0.254.com", queries:"192.168.0.254 login, 192.168.0.254 router, 192.168.0.254 admin, 192.168.0.254 not working", special:"It is part of the 192.168.0.0/16 private range; The same address can exist in many networks."},
  {ip:"192.168.31.1", brands:"Xiaomi router has strong model context; Cannot be guessed at other brands.", use:"Local setup or management address of some Xiaomi routers.", typos:"192.168.l.l, 192.168.31.l, 192.168.3l.1, 192168311", queries:"192.168.31.1 login, Xiaomi 192.168.31.1, 192.168.31.1 setup, 192.168.31.1 not opening", special:"It is important to be connected to the same network in Xiaomi setup; This is not a public Internet login."},
  {ip:"192.168.1.253", brands:"Some travel routers or managed network devices have model-specific context; Not universal brand mapping.", use:"Possible management address of some router, switch or access point.", typos:"192.168.l.253, 192.168.1.25, 192.168.1.254, 192-168-1-253", queries:"192.168.1.253 login, 192.168.1.253 router, 192.168.1.253 admin, 192.168.1.253 not working", special:"Some devices may have different management ports or VLANs; Verify the current gateway."}
];
function makeIpPage(x){
  const ip=x.ip, slug=ip.replaceAll('.', '-');
  return {slug:`/ip/${slug}/`, title:`${ip} Login: Router Admin Troubleshooting | Router Portal`, description:`Learn how to open ${ip} on your local router network, avoid common typos, find the correct gateway, and troubleshoot access safely.`, label:`${ip} router guide`, h1:`${ip} router login`, searchTerms:`${x.typos}, ${x.queries}`, intro:`${x.use} Use it only from the network that owns the device.`, body:`
    <div class="evidence-card"><div class="evidence-head"><strong>Address and access context</strong><span class="status-pill success">COMMON · NOT UNIVERSAL</span></div><div class="evidence-grid"><div><small>Address</small><strong>${ip}</strong></div><div><small>Works from</small><strong>Same network</strong></div><div><small>Credential</small><strong>Model/label</strong></div><div><small>Next check</small><strong>Default Gateway</strong></div></div></div>
    <div class="action-row"><a class="button" href="http://${ip}/">Open ${ip}</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my gateway</a><button class="button ghost" type="button" data-copy-ip="${ip}">Copy IP address</button></div>
    <div class="notice"><strong>Address context:</strong> ${x.special} This is a local/private address, not a public website.</div>
    <h2>What is ${ip} used for?</h2><p>${ip} may open a router, modem, extender, hotspot, switch, or gateway administration screen when your device is connected to the same Wi‑Fi or Ethernet network. The IP alone does not prove a brand, model, password, or ownership.</p>
    <h2>How to open the admin panel</h2><ol><li>Connect your phone or computer to the correct router Wi‑Fi or Ethernet network.</li><li>Open the browser <strong>address bar</strong>, not Google or another search box.</li><li>Type <strong>http://${ip}</strong> and press Enter using the exact dotted form.</li><li>At the login screen, use credentials printed on the device, supplied by the ISP, or previously set by the owner.</li><li>After login, change weak or old administrator credentials and save settings carefully.</li></ol>
    <h2>Brand and device context</h2><p>${x.brands} This is a context clue only. The current Default Gateway shown by your device is more reliable than a generic IP list.</p>
    <h2>Common typing mistakes</h2><p>People may search for <strong>${x.typos}</strong>. Letter <strong>l</strong> and number <strong>1</strong>, or letter <strong>o</strong> and number <strong>0</strong>, are often confused. Search engines may show results for a typo, but the router requires the correct local address.</p>
    <h2>If ${ip} does not open</h2><div class="checklist"><div class="check"><span class="step-no">1</span><div><strong>Confirm the network</strong><span>Stay connected to the router you are trying to manage. Turn off mobile data or another active Wi‑Fi while testing.</span></div></div><div class="check"><span class="step-no">2</span><div><strong>Find the actual gateway</strong><span>Use Windows <code>ipconfig</code>, macOS network details, Linux route information, or your phone’s connected Wi‑Fi details. The gateway may be different.</span></div></div><div class="check"><span class="step-no">3</span><div><strong>Test carefully</strong><span>Check power and cable/Wi‑Fi status, try another browser or Ethernet, and review VPN/proxy or extension interference.</span></div></div></div>
    <h2>Username and password safety</h2><div class="warning"><strong>No universal credential:</strong> Do not assume admin/admin, blank password, or any generic list is correct. Credentials vary by brand, model, firmware, ISP, and previous setup. Router Portal never receives or stores your password.</div>
    <h2>Before a factory reset</h2><p>A reset may erase the Wi‑Fi name, Wi‑Fi password, ISP settings, LAN IP, DHCP reservations, port rules, and security configuration. Treat reset as a last resort and follow exact model instructions. A normal reboot is not the same as a factory reset.</p>
    <h2>Related router help</h2><p><a href="${pageUrl('/router-login-not-working/')}">Router login troubleshooting</a>, <a href="${pageUrl('/forgot-router-password/')}">forgotten password help</a>, <a href="${pageUrl('/factory-reset-router/')}">factory reset warnings</a>, and <a href="${pageUrl('/find-router-ip/')}">find your router IP</a>.</p>
    <p><strong>Search intent covered:</strong> ${x.queries}. This page does not guarantee that every device uses ${ip}.</p>`};
}
const ipPages = ipProfiles.map(makeIpPage);

const brandProfiles = [
  {slug:"tp-link", name:"TP-Link", ips:"192.168.0.1, 192.168.1.1, tplinkwifi.net", models:"Archer C6, Archer C7, TL-WR841N", queries:"TP-Link router login, TP-Link admin password, 192.168.0.1 TP-Link, tplinkwifi.net login", match:"192.168.0.1"},
  {slug:"netgear", name:"NETGEAR", ips:"192.168.1.1, 192.168.0.1, routerlogin.net", models:"R7000, R6700, Nighthawk R8000", queries:"NETGEAR router login, routerlogin.net, NETGEAR admin password, 192.168.1.1 NETGEAR", match:"192.168.1.1"},
  {slug:"d-link", name:"D-Link", ips:"192.168.0.1, 192.168.1.1", models:"DIR-615, DIR-825", queries:"D-Link router login, D-Link admin password, 192.168.0.1 D-Link, DIR-615 login", match:"192.168.0.1"},
  {slug:"linksys", name:"Linksys", ips:"192.168.1.1, myrouter.local", models:"E1200, WRT54G", queries:"Linksys router login, Linksys admin password, 192.168.1.1 Linksys, myrouter.local", match:"192.168.1.1"},
  {slug:"tenda", name:"Tenda", ips:"192.168.0.1, tendawifi.com", models:"AC10, AC23", queries:"Tenda router login, Tenda admin password, 192.168.0.1 Tenda, tendawifi.com login", match:"192.168.0.1"},
  {slug:"huawei", name:"Huawei", ips:"192.168.8.1, 192.168.3.1", models:"B315, B535", queries:"Huawei router login, Huawei Mobile WiFi login, 192.168.8.1 Huawei, Huawei admin password", match:"192.168.8.1"},
  {slug:"asus", name:"ASUS", ips:"192.168.1.1, router.asus.com", models:"RT-AC68U, RT-AX series", queries:"ASUS router login, ASUS admin password, 192.168.1.1 ASUS, router.asus.com", match:"192.168.1.1"},
  {slug:"zte", name:"ZTE", ips:"192.168.1.1, 192.168.0.1", models:"4G/5G home routers, ISP gateways", queries:"ZTE router login, ZTE admin password, 192.168.1.1 ZTE, ZTE modem login", match:"192.168.1.1"},
  {slug:"belkin", name:"Belkin", ips:"192.168.2.1, 192.168.1.1", models:"N300, AC series", queries:"Belkin router login, Belkin admin password, 192.168.2.1 Belkin, Belkin setup", match:"192.168.2.1"},
  {slug:"arris", name:"ARRIS", ips:"192.168.0.1, 192.168.100.1", models:"SURFboard cable gateways", queries:"ARRIS router login, ARRIS modem login, 192.168.0.1 ARRIS, 192.168.100.1 ARRIS", match:"192.168.0.1"},
  {slug:"cisco", name:"Cisco", ips:"192.168.1.1, 192.168.0.1", models:"Linksys/Cisco home gateways, small-office devices", queries:"Cisco router login, Cisco admin password, 192.168.1.1 Cisco, Cisco gateway login", match:"192.168.1.1"},
  {slug:"xiaomi", name:"Xiaomi", ips:"192.168.31.1, miwifi.com", models:"Mi Router 4A, AX series", queries:"Xiaomi router login, Xiaomi admin password, 192.168.31.1 Xiaomi, miwifi.com login", match:"192.168.31.1"}
];
function makeBrandPage(x){
  const brand=x.name, slug=x.slug;
  const ipLinks=x.match.split(',').map(ip => `<a class="ip-chip" href="${pageUrl('/ip/'+ip.trim().replaceAll('.','-')+'/')}">${ip.trim()}</a>`).join(' ');
  return {slug:`/brand/${slug}/`, title:`${brand} Router Login: IP, Admin Password and Setup | Router Portal`, description:`Find ${brand} router login addresses, model context, admin password safety, Wi‑Fi settings and troubleshooting in one simple guide.`, label:`${brand} router guide`, h1:`${brand} router login`, searchTerms:`${x.queries}, ${x.ips}, ${x.models}`, intro:`A practical ${brand} router login guide with model-aware steps and safe credential guidance.`, body:`
    <div class="brand-hero-card"><div><span class="eyebrow">Brand login guide</span><h2>${brand} admin access</h2><p>Use the matching local address only while connected to your own ${brand} router or gateway.</p></div><div class="brand-mark">${brand.slice(0,2).toUpperCase()}</div></div>
    <div class="action-row"><a class="button" href="http://${x.match}/">Open ${x.match}</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my gateway</a><a class="button ghost" href="${pageUrl('/router-login-not-working/')}">Fix login problem</a></div>
    <div class="notice"><strong>Model check first:</strong> ${brand} login addresses, menu names and credentials can change by model, hardware revision, ISP firmware and previous setup. The brand name alone does not guarantee one IP or one password.</div>
    <h2>${brand} router login addresses</h2><p>Common possibilities for this brand include <strong>${x.ips}</strong>. Some models also use a local device name such as a setup hostname. If none opens, do not keep guessing: check the connected device's Default Gateway.</p><div class="brand-links">${ipLinks}</div>
    <h2>Simple login steps</h2><ol><li>Connect your phone or computer to the correct ${brand} router Wi‑Fi or Ethernet network.</li><li>Open the browser address bar, not Google search.</li><li>Enter the matching local IP or local setup address shown for your model.</li><li>Use the administrator credential printed on the label, supplied by your ISP, created during setup, or previously changed by the owner.</li><li>After login, change weak administrator credentials and save a recovery note somewhere private.</li></ol>
    <h2>Default username and password: what is safe to say?</h2><div class="warning"><strong>There is no universal ${brand} password.</strong> Some older or specific devices may show a username such as <strong>admin</strong>, a blank username, or a setup-created account; password examples can include a label-generated key or a model-specific default. These are examples only, not credentials to try blindly. Check the device label, manual, ISP setup sheet, or the exact model guide. Never send your password to Router Portal.</div>
    <h2>Popular model context</h2><div class="grid two-col"><div class="card"><span class="ip-chip">Model examples</span><p>${x.models}</p><a href="${pageUrl('/router-login/')}">Use the general login flow →</a></div><div class="card"><span class="ip-chip">Matching IP guide</span><p>${x.match} may be relevant to one or more ${brand} models, but confirm the current gateway.</p><a href="${pageUrl('/ip/'+x.match.replaceAll('.','-')+'/')}">Open IP guide →</a></div></div>
    <h2>${brand} Wi‑Fi and admin settings</h2><p>After a successful login, common tasks may include changing the Wi‑Fi name, changing the Wi‑Fi password, reviewing connected devices, updating firmware, checking guest access, and reviewing LAN/DHCP settings. Menu labels vary, so read each screen before saving.</p><div class="checklist"><div class="check"><span class="step-no">1</span><div><strong>Change Wi‑Fi safely</strong><span>Use a strong unique Wi‑Fi password and remember that changing it disconnects existing devices.</span></div></div><div class="check"><span class="step-no">2</span><div><strong>Protect the admin account</strong><span>Do not reuse the Wi‑Fi password as the administrator password when the router allows separate values.</span></div></div><div class="check"><span class="step-no">3</span><div><strong>Keep settings before reset</strong><span>A factory reset can erase ISP, LAN, Wi‑Fi, port and security settings.</span></div></div></div>
    <h2>${brand} login not working?</h2><p>Confirm the network, read the current Default Gateway, try Ethernet or another browser, review VPN/proxy interference, and check whether the ISP has changed the router firmware. A normal reboot is safer than a factory reset; reset only after reading the exact model instructions.</p>
    <h2>Related Router Portal pages</h2><p><a href="${pageUrl('/change-wifi-password/')}">Change Wi‑Fi password</a>, <a href="${pageUrl('/forgot-router-password/')}">forgot admin password</a>, <a href="${pageUrl('/factory-reset-router/')}">factory reset warning</a>, and <a href="${pageUrl('/router-login-not-working/')}">router login troubleshooting</a>.</p>
    <p><strong>Search intent covered:</strong> ${x.queries}.</p>`};
}
const brandPages = brandProfiles.map(makeBrandPage);

const pages = [
  {
    slug: '/',
    title: 'Router Login Help: IP, Admin Access',
    description: 'Simple router login help for 192.168.1.1, 192.168.0.1, 10.0.0.1, router IP discovery and common admin access problems.',
    label: 'A clearer way to reach your router',
    h1: 'Find your router login page',
    intro: 'Enter a router IP, brand, model, or problem and get a short, practical next step without the clutter.',
    home: true,
    body: `
      <section class="section demo-section" id="help"><div class="container"><div class="section-head"><div><h2>Start with what you see</h2><p>No need to know technical terms first.</p></div><a class="view" href="${pageUrl('/all-guides/')}">All help →</a></div><div class="help-grid"><a class="help-card" href="${pageUrl('/router-login/')}"><div class="help-icon">🔐</div><h3>Router Login <span class="go">→</span></h3><p>Cannot open 192.168.1.1 or another admin page?</p></a><a class="help-card" href="${pageUrl('/router-login-not-working/')}"><div class="help-icon">📶</div><h3>Wi-Fi Problems <span class="go">→</span></h3><p>Slow, disconnected, weak signal or no internet.</p></a><a class="help-card" href="${pageUrl('/setup/new-router-setup-checklist/')}"><div class="help-icon">⚙️</div><h3>Router Setup <span class="go">→</span></h3><p>Configure a new router with guided steps.</p></a><a class="help-card" href="${pageUrl('/find-router-ip/')}"><div class="help-icon">🌐</div><h3>IP &amp; Gateway <span class="go">→</span></h3><p>Find the address your phone or computer uses.</p></a><a class="help-card" href="${pageUrl('/forgot-router-password/')}"><div class="help-icon">🔑</div><h3>Password Help <span class="go">→</span></h3><p>Change Wi-Fi credentials or access settings.</p></a><a class="help-card" href="${pageUrl('/router-login-not-working/')}"><div class="help-icon">🛠️</div><h3>Troubleshooting <span class="go">→</span></h3><p>Follow a simple decision path to the likely fix.</p></a></div></div></section>
      <section class="section demo-section" id="zone"><div class="container"><div class="section-head"><div><h2>Problem Solver</h2><p>A future-friendly flow: identify → check → fix.</p></div></div><div class="zone"><div class="zone-card"><h3>What is happening?</h3><p class="small-muted">Choose the closest match and open a focused guide.</p><div class="toolrow"><a class="tool" href="${pageUrl('/router-login-not-working/')}">🌐 Internet not working</a><a class="tool" href="${pageUrl('/router-login/')}">🔐 Cannot login</a><a class="tool" href="${pageUrl('/wifi/slow-wifi-diagnosis/')}">📶 Wi-Fi is slow</a><a class="tool" href="${pageUrl('/setup/new-router-setup-checklist/')}">⚙️ New router</a></div></div><div class="zone-card"><h3>Network check</h3><p class="small-muted">A visual pattern for lightweight checks and guidance.</p><div class="mini-status"><div><small>Connection</small><b>Guide mode</b></div><div><small>Gateway</small><b>Find yours</b></div><div><small>Scope</small><b>Wi-Fi</b></div></div></div></div></div></section>
      <section class="section demo-section" id="guides"><div class="container"><div class="section-head"><div><h2>Popular solutions</h2><p>Useful first. News and filler stay out.</p></div></div><div class="guide-list"><a class="guide" href="${pageUrl('/ip/192-168-1-1/')}"><span class="num">01</span><div><b>192.168.1.1 not opening</b><small>Login · 4 min</small></div></a><a class="guide" href="${pageUrl('/find-router-ip/')}"><span class="num">02</span><div><b>Find your current router IP</b><small>IP &amp; Gateway · 3 min</small></div></a><a class="guide" href="${pageUrl('/change-wifi-password/')}"><span class="num">03</span><div><b>Change Wi-Fi password</b><small>Wi-Fi · 4 min</small></div></a><a class="guide" href="${pageUrl('/router-login-not-working/')}"><span class="num">04</span><div><b>No internet after setup</b><small>Troubleshooting · 5 min</small></div></a></div></div></section>
      <section class="section demo-section" id="brands"><div class="container"><div class="section-head"><div><h2>Router brands</h2><p>Brand-aware navigation for a growing knowledge base.</p></div></div><div class="brands"><a class="brand" href="${pageUrl('/brand/tp-link/')}">TP-Link</a><a class="brand" href="${pageUrl('/brand/tenda/')}">Tenda</a><a class="brand" href="${pageUrl('/brand/d-link/')}">D-Link</a><a class="brand" href="${pageUrl('/brand/asus/')}">ASUS</a><a class="brand" href="${pageUrl('/brand/netgear/')}">Netgear</a><a class="brand" href="${pageUrl('/brand/xiaomi/')}">Xiaomi</a><a class="brand" href="${pageUrl('/brand/huawei/')}">Huawei</a><a class="brand" href="${pageUrl('/brand/zte/')}">ZTE</a><a class="brand" href="${pageUrl('/brand-router-model-search/')}">More brands +</a></div></div></section>
      <section class="section demo-section" id="article"><div class="container"><div class="section-head"><div><h2>Inside a real guide</h2><p>Focused content layout users can understand immediately.</p></div></div><article class="article"><aside class="toc"><b>ON THIS PAGE</b><a href="${pageUrl('/router-login/')}">Quick answer</a><a href="${pageUrl('/router-login/')}">Connect</a><a href="${pageUrl('/find-router-ip/')}">Find IP</a><a href="${pageUrl('/router-login/')}">Login</a><a href="${pageUrl('/router-login-not-working/')}">Troubleshoot</a></aside><div><div class="tags"><span class="tag">Router Login</span><span class="tag">Beginner</span><span class="tag">Updated</span></div><h2 class="article-title">How to Log In to Your Router</h2><div class="answer"><strong>Quick Answer</strong><br>Connect to the router's network, find its current gateway address, open it in your browser, then enter the correct admin credentials.</div><h3>Step-by-step</h3><ol><li>Connect your phone or computer to the router.</li><li>Find the current gateway / local router address.</li><li>Open the address directly in the browser.</li><li>Use the router's admin credentials.</li></ol><div class="steps"><div class="step"><span class="badge">✓</span><span><b>Helpful note:</b> the address printed on the router and the current gateway can differ.</span></div><div class="step"><span class="badge">!</span><span><b>Still stuck?</b> move to the troubleshooting guide instead of reading a huge article.</span></div></div></div></article></div></section>
      <section class="section demo-section future" id="future"><div class="container"><div class="future-card"><h2>Future-ready foundation</h2><p>These are system ideas for a site that grows for years—not decorative counters.</p><div class="future-grid"><div class="future-stat"><small>Guide library</small><b>Scalable</b></div><div class="future-stat"><small>Search</small><b>Problem-first</b></div><div class="future-stat"><small>UX</small><b>Mobile-first</b></div><div class="future-stat"><small>Content</small><b>Focused</b></div></div></div></div></section>
      <section class="section demo-section" id="about"><div class="container"><div class="zone-card"><h2>About Router Portal</h2><p class="about-copy">A focused resource for router login, setup, Wi-Fi, networking and troubleshooting. The interface is designed to help users reach an answer without clutter, forced desktop mode or unnecessary news.</p></div></div></section>
      <section class="section demo-section"><div class="container"><div class="notice"><strong>Safety first:</strong> Router Portal never asks for your router password. Use local admin instructions only for a router and network you own or are authorised to manage.</div></div></section>`
  },
  {
    slug: '/router-login/', title: 'How to Log In to Your Router | Router Portal', description: 'Learn how to open your router admin page, find the correct gateway, use the right credentials, and fix common router login problems safely.', label: 'Router admin access', h1: 'How to log in to your router', intro: 'Open your router control panel from your own local network. Router Portal never asks for or handles your password.', body: `
      <div class="answer-lead"><strong>Quick answer:</strong> Connect to your router’s Wi-Fi or Ethernet network, find its current Default Gateway, and type that local address into your browser’s address bar. Common examples include <strong>192.168.1.1</strong> and <strong>192.168.0.1</strong>, but your device’s gateway is the reliable answer.</div>
      <div class="action-row"><a class="button" href="http://192.168.1.1/">Open 192.168.1.1</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my router IP</a></div>
      <div class="notice"><strong>Before you start:</strong> Connect to the router you own or are authorised to manage. Type the address into the browser address bar—not into Google Search. A local admin page normally works only from that router’s network.</div>
      <h2>How to log in to your router</h2><ol><li>Connect your phone or computer to the correct router network by Wi-Fi or Ethernet.</li><li>Find the network’s <strong>Default Gateway</strong> if you do not know the router IP.</li><li>Open a browser and type the exact local address in the address bar, such as <strong>http://192.168.1.1</strong>.</li><li>Press Enter and use the username or password printed on the router label, supplied by your ISP, or created during setup.</li><li>After signing in, review security settings and replace weak or unchanged administrator credentials.</li></ol>
      <h2>Router admin password vs Wi-Fi password</h2><div class="grid two-col"><div class="card"><span class="ip-chip">Admin password</span><p>Opens the router’s settings panel. It may be printed on the device or created during setup.</p></div><div class="card"><span class="ip-chip">Wi-Fi password</span><p>Connects phones, computers, and other devices to the wireless network. It is not always the same as the admin password.</p></div></div>
      <h2>Try another common address</h2><div class="grid two-col"><div class="card"><span class="ip-chip">192.168.0.1</span><p>Common on some D-Link, TP-Link, and other home routers. Use it only while connected to the relevant network.</p><a href="${pageUrl('/ip/192-168-0-1/')}">Read the 192.168.0.1 guide →</a></div><div class="card"><span class="ip-chip">10.0.0.1</span><p>Used by some gateways and ISP equipment. Check the actual gateway instead of guessing repeatedly.</p><a href="${pageUrl('/ip/10-0-0-1/')}">Read the 10.0.0.1 guide →</a></div></div>
      <h2>Router login FAQ</h2><div class="faq-list"><details><summary>Why does 192.168.1.1 not open?</summary><p>Your router may use a different gateway, or your device may be on mobile data, another Wi-Fi network, or a guest network. <a href="${pageUrl('/find-router-ip/')}">Find the current gateway</a> first.</p></details><details><summary>Should I search for the IP in Google?</summary><p>No. Type the local address directly into the browser address bar. Searching for it can lead to unrelated results instead of your router’s local login screen.</p></details><details><summary>Is the router admin password the same as the Wi-Fi password?</summary><p>Not necessarily. The admin password opens settings; the Wi-Fi password joins the wireless network. Check the label or setup record for the correct credential.</p></details></div>
      <h2>Do not enter your password on this website</h2><p>Router Portal is an information site. It never receives, stores, or processes router credentials. Use only the login page served by your own router, and follow the relevant manufacturer or ISP instructions when a model-specific step is required.</p><div class="action-row"><a class="button ghost" href="${pageUrl('/router-login-not-working/')}">Login is not working</a><a class="button secondary" href="${pageUrl('/editorial-policy/')}">How we check information</a></div>`
  },
  {
    slug: '/find-router-ip/', title: 'Find Your Router IP Address and Default Gateway | Router Portal', description: 'Find the router IP or default gateway on Windows, macOS, Android, iPhone, iPad and Linux with simple steps.', label: 'Find the right local address', h1: 'How to find your router IP address', intro: 'The correct gateway shown by your device is more reliable than guessing a common IP.', body: `
      <h2>Windows</h2><ol><li>Open Command Prompt.</li><li>Run <code>ipconfig</code>.</li><li>Look for <strong>Default Gateway</strong> under the connected adapter.</li></ol><h2>macOS</h2><ol><li>Open System Settings and choose your connected network.</li><li>Open network details and look for Router.</li></ol><h2>Android and iPhone</h2><p>Open the details for the Wi-Fi network you are currently using. Look for Gateway, Router, or similar wording. The label varies by device and version.</p><h2>Linux</h2><p>Open a terminal and check the default route with your network tools. The address after <strong>default via</strong> is normally the gateway.</p><div class="warning"><strong>Important:</strong> The gateway may be different from the popular examples. Use the value shown for your current network.</div><div class="action-row"><a class="button" href="${pageUrl('/router-login/')}">Open the login guide</a><a class="button secondary" href="${pageUrl('/router-login-not-working/')}">Need another fix?</a></div>`
  },
  {
    slug: '/router-login-not-working/', title: 'Router Login Not Working: Fix the Admin Page | Router Portal', description: 'Fix a router login page that will not open. Check your connection, gateway, browser, and reset options step by step.', label: 'Troubleshooting', h1: 'Router login is not working', intro: 'Work through these checks in order before considering a factory reset.', body: `
      <div class="checklist"><div class="check"><span class="step-no">1</span><div><strong>Check the connection</strong><span>Make sure your device is connected to the router’s Wi-Fi or Ethernet network.</span></div></div><div class="check"><span class="step-no">2</span><div><strong>Check the address</strong><span>Use your device’s Default Gateway instead of guessing an IP.</span></div></div><div class="check"><span class="step-no">3</span><div><strong>Use the address bar</strong><span>Type the local address directly into the browser address bar.</span></div></div><div class="check"><span class="step-no">4</span><div><strong>Try another browser</strong><span>Disable a VPN temporarily and test a private window if appropriate.</span></div></div></div><h2>Still cannot open it?</h2><p>Restart the router and wait for it to finish starting. Check the label or setup information for the correct local address. A factory reset can erase your network settings, so do not use it as the first fix.</p><div class="warning"><strong>Reset warning:</strong> Only reset a router when you understand that the Wi-Fi name, password, ISP settings, and custom rules may be removed.</div><h2>What the error usually means</h2><p>A timeout often points to the wrong local network or gateway; a refused connection can indicate that the router uses a different protocol or management port. Compare the device gateway, model documentation, and connection status before changing settings.</p><div class="action-row"><a class="button" href="${pageUrl('/find-router-ip/')}">Find the gateway</a><a class="button secondary" href="${pageUrl('/factory-reset-router/')}">Understand reset first</a></div>`
  },
  {
    slug: '/forgot-router-password/', title: 'Forgot Router Admin Password? Safe Recovery Steps | Router Portal', description: 'Forgot your router admin password? Learn the difference between admin and Wi-Fi passwords and the safest next steps.', label: 'Password recovery', h1: 'Forgot your router admin password?', intro: 'First identify which password you forgot. The admin password and Wi-Fi password are often different.', body: `
      <h2>Admin password or Wi-Fi password?</h2><p>The admin password opens the router settings page. The Wi-Fi password connects a device to the network. Changing one does not always change the other.</p><h2>Try the safe options first</h2><ol><li>Check the router label or setup record.</li><li>Ask the person who configured the router.</li><li>Use the router’s documented recovery flow if one exists.</li><li>Back up settings before making a change.</li></ol><div class="warning"><strong>Before resetting:</strong> A factory reset may erase ISP settings, Wi-Fi names, passwords, port rules, and parental controls.</div><h2>After a reset</h2><p>Reconnect using the setup instructions for your model, create a new strong admin password, and change the default Wi-Fi password.</p><div class="action-row"><a class="button" href="${pageUrl('/factory-reset-router/')}">Read reset warnings</a><a class="button secondary" href="${pageUrl('/router-login/')}">Return to login steps</a></div>`
  },
  {
    slug: '/change-wifi-password/', title: 'How to Change Your Wi-Fi Password Safely | Router Portal', description: 'Change your Wi-Fi password from a router admin page with a simple, safe checklist.', label: 'Wi-Fi settings', h1: 'Change your Wi-Fi password', intro: 'Use the router settings page on your own network, then reconnect your devices with the new password.', body: `
      <h2>General steps</h2><ol><li>Connect to your router network.</li><li>Open the router admin page using its local IP.</li><li>Sign in with the router’s admin credentials.</li><li>Open Wireless, Wi-Fi, WLAN, or Security settings.</li><li>Choose a strong new password and save.</li><li>Reconnect phones, computers, TVs, and other devices.</li></ol><h2>Choose a safer password</h2><p>Use a long, unique password that is not your name, address, phone number, or router brand. Do not reuse a sensitive account password.</p><div class="notice"><strong>Connection note:</strong> Saving wireless settings may disconnect the device briefly. Reconnect using the new password.</div><div class="action-row"><a class="button" href="${pageUrl('/router-login/')}">Open login steps</a><a class="button secondary" href="${pageUrl('/router-login-not-working/')}">Need login help?</a></div>`
  },
  {
    slug: '/factory-reset-router/', title: 'How to Factory Reset a Router: Warnings and Next Steps | Router Portal', description: 'Understand what a router factory reset removes, when to use it, and what to prepare before pressing reset.', label: 'Use with care', h1: 'Factory reset a router carefully', intro: 'A factory reset is a last-resort action that can remove your network configuration.', body: `
      <div class="warning"><strong>Do not reset first.</strong> A reset can erase your Wi-Fi name, Wi-Fi password, ISP configuration, admin password, port forwarding, and custom rules.</div><h2>Before pressing reset</h2><ul><li>Find the model and setup information.</li><li>Record settings you will need again.</li><li>Check whether a simple restart or gateway correction solves the problem.</li><li>Make sure you know how to set up the connection afterward.</li></ul><h2>General reset process</h2><ol><li>Keep the router powered on.</li><li>Use the reset control specified for your model.</li><li>Hold it only for the documented duration.</li><li>Wait for the router to restart fully.</li><li>Run the initial setup and create new passwords.</li></ol><p>The exact reset method differs by model. Do not use a random timing rule when you are unsure.</p><div class="action-row"><a class="button secondary" href="${pageUrl('/router-login-not-working/')}">Try login fixes first</a><a class="button" href="${pageUrl('/find-router-ip/')}">Find the gateway</a></div>`
  },
  {
    slug: '/ip/192-168-1-1/', title: '192.168.1.1 Login: Router Admin Troubleshooting | Router Portal', description: 'Open 192.168.1.1 router admin login, avoid 192.168.l.l typos, find your gateway, and fix common access problems.', label: 'Most searched router IP', h1: '192.168.1.1 router login', intro: 'Use this local address from your own router network. Type it into the browser address bar, not a search engine.', body: `
      <div class="evidence-card"><div class="evidence-head"><strong>Address and access context</strong><span class="status-pill success">COMMON · NOT UNIVERSAL</span></div><div class="evidence-grid"><div><small>Address</small><strong>192.168.1.1</strong></div><div><small>Works from</small><strong>Same network</strong></div><div><small>Credential</small><strong>Model/label</strong></div><div><small>Next check</small><strong>Default Gateway</strong></div></div></div><div class="action-row"><a class="button" href="http://192.168.1.1/">Open 192.168.1.1</a><a class="button secondary" href="${pageUrl('/find-router-ip/')}">Find my gateway</a><button class="button ghost" type="button" data-copy-ip="192.168.1.1">Copy IP address</button></div><div class="notice"><strong>Correct address:</strong> <span class="ip-large">192.168.1.1</span>. Common typing mistakes include 192.168.l.l, 192.168.1.1. and 19216811.</div><div class="answer-lead quick-answer"><strong>Quick answer:</strong> Connect to the correct router network, type <strong>http://192.168.1.1</strong> in the browser address bar, use the credential for the exact device, and check the current gateway before resetting if the page does not open.</div><h2>How to log in</h2><ol><li>Connect your device to the router’s Wi-Fi or Ethernet network.</li><li>Type <strong>192.168.1.1</strong> in the browser address bar.</li><li>Press Enter and wait for the router login screen.</li><li>Use the credentials printed on your router label or setup information.</li><li>After signing in, change the default admin password if the router still uses one.</li></ol><h2>If 192.168.1.1 does not open</h2><ul><li>Confirm that your device is connected to the correct router.</li><li>Find the Default Gateway shown by your device instead of guessing.</li><li>Temporarily check VPN or browser issues.</li><li>Do not factory-reset the router as the first step.</li></ul><div class="warning"><strong>Credential safety:</strong> Router Portal never asks for or stores your router username or password. Default credentials vary by model and firmware.</div><h2>Private address, not a public website</h2><p>192.168.1.1 is normally a local network address. It works only when your device can reach the router that uses it. If your gateway is different, use the address shown by your device.</p><div class="action-row"><a class="button ghost" href="${pageUrl('/router-login-not-working/')}">Login is not working</a><a class="button secondary" href="${pageUrl('/factory-reset-router/')}">Read reset warning</a></div>`
  },
  {
    slug: '/about/', schemaType: 'AboutPage', title: 'About Router Portal: Owner & Contact | Router Portal', description: 'Meet Router Portal founder and CEO Md Juyel, learn what the site does, and find official contact and collaboration details.', label: 'About Router Portal', h1: 'About Router Portal', intro: 'Meet the founder, understand our purpose, and find official ways to contact Router Portal.', body: `
      <div class="founder-profile"><img class="founder-photo" src="${pageUrl('/assets/founder-md-juyel.jpg')}" alt="Md Juyel, Founder and CEO of Router Portal" width="900" height="900" loading="eager"><div><span class="eyebrow">Founder &amp; CEO</span><h2>Md Juyel</h2><p>Md Juyel is the Founder and CEO of Router Portal, an independent online resource created to make router login, home networking, Wi-Fi troubleshooting, and internet connectivity topics easier to understand. Through Router Portal, he focuses on providing clear, practical, and safety-conscious guidance for readers worldwide.</p><p><strong>Founded:</strong> 2026 · <strong>Audience:</strong> Worldwide</p></div></div><h2>What Router Portal is</h2><p>Router Portal is an independent information website about router login addresses, local network access, gateway discovery, Wi-Fi settings, home-network security, and common router problems.</p><h2>Our editorial approach</h2><p>We aim to answer practical questions clearly while explaining where router model, hardware revision, firmware, region, or ISP settings can change the result. Pages are reviewed for clarity, safety warnings, broken links, misleading universal claims, and useful next steps.</p><ul><li>We distinguish common examples from model-specific facts.</li><li>We warn before destructive actions such as factory reset.</li><li>We use official manufacturer or provider context when a claim depends on a specific device.</li><li>We do not ask visitors to submit passwords or private network data.</li></ul><h2>What we do not do</h2><ul><li>We do not log in to your router.</li><li>We do not collect or store your router username, admin password, or Wi-Fi password.</li><li>We are not an official router manufacturer, ISP, or brand support channel.</li><li>We do not promise that one IP address or credential works for every model or network.</li></ul><div class="notice"><strong>Use the guide safely:</strong> Follow local-network instructions only for a router you own or are authorised to manage.</div><h2>Official contact</h2><div class="contact-links"><p><strong>General, collaboration and business inquiries:</strong><br><a href="mailto:routerportals@gmail.com">routerportals@gmail.com</a></p><p><strong>WhatsApp:</strong><br><a href="https://wa.me/8801332369029" rel="noopener">+880 1332-369029</a></p><p><strong>Facebook:</strong><br><a href="https://www.facebook.com/share/1G6Bz6U17h/" rel="me noopener">Md Juyel on Facebook</a></p></div><p>For corrections, include the page URL, the part that may be wrong, and a short explanation. Do not send router passwords, Wi-Fi keys, MAC addresses, serial numbers, public IPs, or private screenshots.</p>`
  },
  {
    slug: '/contact/', title: 'Contact Router Portal: Email, WhatsApp & Facebook | Router Portal', description: 'Contact Router Portal for corrections, collaborations, business inquiries, and updates without sharing private router credentials.', label: 'Contact Router Portal', h1: 'Contact Router Portal', intro: 'Send corrections, collaboration requests, or business inquiries through an official contact channel.', body: `
      <div class="contact-links"><h2>Email</h2><p>For general questions, collaboration, corrections and business inquiries:</p><p><a class="button" href="mailto:routerportals@gmail.com">routerportals@gmail.com</a></p><h2>WhatsApp</h2><p>For business purposes or direct contact:</p><p><a class="button secondary" href="https://wa.me/8801332369029" rel="noopener">Message +880 1332-369029</a></p><h2>Facebook</h2><p><a class="button ghost" href="https://www.facebook.com/share/1G6Bz6U17h/" rel="me noopener">Visit Md Juyel on Facebook</a></p></div><h2>For corrections or updates</h2><ol><li>The exact Router Portal page URL.</li><li>The sentence or step that appears incorrect.</li><li>A short explanation of the correction.</li><li>The router brand and model only when it is relevant.</li></ol><h2>Never include</h2><div class="warning"><strong>Do not send private access information.</strong> Never include a router username, password, Wi-Fi password, public IP, MAC address, serial number, account number, or screenshot containing private network data.</div><h2>What happens next</h2><p>A correction is reviewed against the page purpose and the relevant router or network context. A change may be made when the information is clear and verifiable; not every suggestion will be accepted as a universal rule.</p>`
  },
  {
    slug: '/editorial-policy/', title: 'Router Portal Editorial Policy and Review Process | Router Portal', description: 'Read Router Portal’s editorial rules for accuracy, clarity, safety warnings, updates, and corrections.', label: 'Editorial standards', h1: 'How Router Portal pages are reviewed', intro: 'Our editorial process prioritises useful steps, clear caveats, and safe local-router guidance over keyword repetition.', body: `
      <h2>Our editorial priorities</h2><ol><li>Answer the user’s immediate question early.</li><li>Use plain language before technical terminology.</li><li>Separate a common example from a guaranteed rule.</li><li>Warn before destructive actions such as factory reset.</li><li>Never ask a visitor to submit router credentials.</li></ol><h2>Research and verification</h2><p>Router Portal content is prepared by comparing the user problem, router and network terminology, device instructions, manufacturer context, and existing help patterns. Competitor pages may help identify user needs and gaps, but their wording, screenshots, tables, and layout are not copied.</p><h2>Updates and corrections</h2><p>Router details can differ by model, firmware, region, and ISP. Pages may be updated when a fact changes, a safer instruction becomes available, or a correction is supported by clear evidence. Pages may include a review note as the content system expands.</p><h2>Use of assistance tools</h2><p>Writing and code assistance may be used during preparation, but pages are reviewed for accuracy, safety, duplicate wording, broken links, and misleading universal claims before publication.</p><h2>Independence</h2><p>Router Portal is not an official manufacturer or internet-provider support channel and should not be mistaken for one.</p>`
  },
  {
    slug: '/information-policy/', title: 'Router Portal Information Policy: Accuracy and Updates | Router Portal', description: 'Understand how Router Portal organises router IP, admin login, troubleshooting, and network information for readers.', label: 'Information policy', h1: 'Information that is clear about its limits', intro: 'Router and network instructions are useful only when their limits are explained. Router Portal separates common examples from model-specific facts.', body: `
      <h2>Common information versus model-specific information</h2><p>Addresses such as 192.168.1.1 are common examples, not a guarantee for every router. A device’s current Default Gateway is often more reliable than guessing from a popular list.</p><h2>Credential information</h2><p>Router Portal does not present a universal username and password as guaranteed. Credentials can vary by model, firmware, setup process, and whether someone changed the default.</p><h2>Safety boundaries</h2><ul><li>Local admin links should be opened only while connected to the relevant network.</li><li>Do not enter router credentials into Router Portal.</li><li>Do not factory-reset before understanding what settings will be removed.</li><li>Do not apply a model-specific instruction to a different model without checking the context.</li></ul><h2>How we handle uncertainty</h2><p>When a detail cannot safely be stated as universal, the page says so and points the reader toward finding the current gateway, checking the device label, or using the model context. Unknown information is not filled with invented certainty.</p><h2>Page improvement</h2><p>New pages and revisions are added in small groups so that metadata, internal links, content quality, and safety wording can be checked together.</p>`
  },
  {
    slug: '/privacy/', title: 'Router Portal Privacy Notice and Data Safety | Router Portal', description: 'Read how Router Portal handles privacy, router credentials, local network information, and visitor data in this static website.', label: 'Privacy', h1: 'Your router credentials stay with you', intro: 'Router Portal is designed to provide information without asking for router passwords or private network details.', body: `
      <h2>Information we do not request</h2><ul><li>Router admin username or password.</li><li>Wi-Fi password or security key.</li><li>Public IP, MAC address, serial number, or ISP account details.</li><li>Private network screenshots containing sensitive information.</li></ul><h2>Static website design</h2><p>The first release is a static information site. It has no visitor account, no router login system, and no form that sends router credentials to us.</p><h2>Local links</h2><p>Buttons such as “Open 192.168.1.1” point to a local address in the visitor’s browser. Router Portal does not receive the router admin page or its password.</p><h2>Technical hosting data</h2><p>Like most public websites, the hosting and delivery platform may process technical request information needed to deliver pages, protect the service, and maintain reliability. Router Portal does not intentionally use the site to collect router secrets.</p><h2>Changes to this notice</h2><p>This notice may be updated when the site adds a feature that changes data handling. Any new form, analytics, or tool will be reviewed before it is added.</p>`
  },
  {
    slug: '/terms/', title: 'Router Portal Terms of Use and Safety Disclaimer | Router Portal', description: 'Read the Router Portal terms of use, local-router safety disclaimer, accuracy limits, and responsible access rules.', label: 'Terms of use', h1: 'Use Router Portal responsibly', intro: 'Router Portal provides general information. You are responsible for confirming that an instruction fits your own router, network, and permission level.', body: `
      <h2>Informational use</h2><p>Router Portal pages are general educational and troubleshooting information. They are not a guarantee that a specific IP, credential, setting, or reset process applies to every router.</p><h2>Authorised access only</h2><p>Use local admin instructions only for a router and network you own or are authorised to manage. Do not use the guides to access someone else’s network.</p><h2>Before changing settings</h2><ul><li>Confirm the router model and current network.</li><li>Keep setup information available.</li><li>Understand what a change or reset may remove.</li><li>Do not share passwords or private network identifiers with this site.</li></ul><h2>Accuracy limits</h2><p>Router interfaces and instructions can change with model, firmware, region, and provider configuration. When a page says an address is common, it does not mean that address is guaranteed for your device.</p><h2>External destinations</h2><p>A local-router button may open an address on your own network. Router Portal does not control that router interface or its content.</p><h2>Acceptance</h2><p>By using the website, you agree to use the information lawfully, safely, and with appropriate permission.</p>`
  }
  ,...ipPages
  ,...brandPages
	  ,...makeRecommendedPages(pageUrl)
	  ,...makeFiftyPages(pageUrl)
	  ,...makeNewPages(pageUrl)
  ,...makeModelPages(pageUrl)
	  ,...makeVersionTwoPages(pageUrl)
	  ,...makeAdditionalIpPages(pageUrl)
	  ,...makeIpPages50(pageUrl)
	  ,...makeIpPages100(pageUrl)
	  ,...makeIpPages200(pageUrl)
];
const allGuideLinks = pages.map(p => `<li><a href="${pageUrl(p.slug)}">${p.h1}</a><span>${p.label}</span></li>`).join('');
pages.push({ slug:'/all-guides/', title:'All Router Guides and Tools | Router Portal', description:'Browse every Router Portal guide, tool, router IP page, brand page, model page, Wi-Fi guide, and security resource in one directory.', label:'All Router Portal guides', h1:'Browse all router guides and tools', intro:'Use the directory or search to reach every Router Portal page, tool, and topic cluster.', searchTerms:'all router guides, router tools directory, router IP guides, Wi-Fi guides, network security guides', body:`<div class="answer-lead"><strong>Find any page:</strong> Browse the complete Router Portal directory below, or use the site search to find a router IP, model, tool, Wi-Fi topic, or troubleshooting guide.</div><div class="guide-directory"><ul>${allGuideLinks}</ul></div><div class="notice"><strong>Safety reminder:</strong> Use router instructions only for a device and network you own or are authorised to manage. Never send Router Portal a router password or Wi-Fi key.</div>`});
const duplicateSlugs = pages.map(p => p.slug).filter((slug, i, all) => all.indexOf(slug) !== i);
if (duplicateSlugs.length) throw new Error(`Duplicate page slugs: ${[...new Set(duplicateSlugs)].join(', ')}`);
function ipCard(label, text, href){ return `<div class="card"><span class="ip-chip">${label}</span><p>${text}</p><a href="${pageUrl(href)}">View the guide →</a></div>`; }
function escapeHtml(value){ return value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
	function seoTitle(value){ const base=String(value).replace(/\s+/g,' ').trim().replace(/\s*\|\s*Router Portal$/i,'').trim(); if(base.length<30) return `${base} | Router Portal`; if(base.length<=60) return base; return `${base.slice(0,60).replace(/\s+\S*$/,'').trim()}`; }
function seoDescription(value){ let text=String(value).replace(/\s+/g,' ').trim(); if(text.length<50) text=`${text} Safe steps, limits and source notes included.`; if(text.length<=160) return text; return `${text.slice(0,158).replace(/\s+\S*$/,'').trim()}…`; }
function header(){
  const desktopItems = `<a href="${pageUrl('/router-login/')}">Router Help</a><a href="${pageUrl('/router-login-not-working/')}">Problem Solver</a><a href="${pageUrl('/all-guides/')}">Guides</a><a href="${pageUrl('/brand-router-model-search/')}">Brands</a><a href="${pageUrl('/about/')}">About</a>`;
  const mobileItems = `<a href="${pageUrl('/')}">Home</a><a href="${pageUrl('/router-login/')}">Router Help</a><a href="${pageUrl('/router-login-not-working/')}">Problem Solver</a><a href="${pageUrl('/all-guides/')}">Guides</a><a href="${pageUrl('/brand-router-model-search/')}">Brands</a><a href="${pageUrl('/about/')}">About</a>`;
  return `<div class="portal-topbar">Router Portal · Practical help for your router, Wi-Fi and local network</div><header class="site-header"><nav class="nav" aria-label="Primary navigation"><a class="site-brand" href="${pageUrl('/')}" aria-label="Router Portal home"><img src="${pageUrl('/assets/logo-wifi.png')}" alt="Router Portal Wi-Fi logo" width="48" height="48"><span class="brand-name">Router <em>Portal</em></span></a><div class="portal-desktop-nav">${desktopItems}</div><div class="portal-search-label">⌕&nbsp; Search portal</div><details class="mobile-menu"><summary>Menu</summary><div class="mobile-menu-panel">${mobileItems}</div></details></nav></header>`;
}
function bottomNav(){ return `<nav class="bottom-nav" aria-label="Mobile portal navigation"><a class="active" href="${pageUrl('/')}"><span>⌂</span>Home</a><a href="${pageUrl('/router-login/')}"><span>◉</span>Help</a><a href="${pageUrl('/router-login-not-working/')}"><span>⌁</span>Diagnose</a><a href="${pageUrl('/brand-router-model-search/')}"><span>▦</span>Brands</a></nav>`; }
function footer(){ return `<footer class="site-footer"><div class="footer-inner"><div><a class="site-brand" href="${pageUrl('/')}" aria-label="Router Portal home"><img src="${pageUrl('/assets/logo-wifi.png')}" alt="Router Portal Wi-Fi logo" width="48" height="48"><span class="brand-name">Router Portal</span></a><p>Simple, safety-first help for router IP addresses, admin access, and home-network problems.</p><a class="footer-directory" href="${pageUrl('/all-guides/')}">Explore the complete guide directory →</a></div><div><strong>Help</strong><p><a href="${pageUrl('/router-login/')}">Router login</a><br><a href="${pageUrl('/find-router-ip/')}">Find your router IP</a><br><a href="${pageUrl('/router-login-not-working/')}">Fix login problems</a><br><a href="${pageUrl('/ip/192-168-1-1/')}">192.168.1.1 guide</a></p></div><div><strong>Explore</strong><p><a href="${pageUrl('/brand-router-model-search/')}">Brands and models</a><br><a href="${pageUrl('/tools/what-is-my-ip/')}">Tools</a><br><a href="${pageUrl('/wifi/wi-fi-7-explained/')}">Wi-Fi guides</a><br><a href="${pageUrl('/security/router-firewall-basics/')}">Security guides</a></p></div><div><strong>Trust</strong><p><a href="${pageUrl('/about/')}">About</a> · <a href="${pageUrl('/contact/')}">Corrections</a><br><a href="${pageUrl('/editorial-policy/')}">Editorial policy</a><br><a href="${pageUrl('/privacy/')}">Privacy</a> · <a href="${pageUrl('/terms/')}">Terms</a></p></div></div></footer>`; }
function searchBox(){ return `<div class="search-wrap"><form class="search-shell" id="site-search"><label class="sr-only" for="search-input">Search router help</label><input id="search-input" autocomplete="off" placeholder="Try 192.168.1.1 or router login problem"><button class="button" type="submit">Search</button></form><div id="search-results" class="search-results" aria-live="polite"></div></div>`; }
function layout(page){
  const title=seoTitle(page.title);
  const description=seoDescription(page.description);
  const hero = page.home ? `<section class="hero demo-hero"><div class="container hero-grid"><div><div class="breadcrumb">Home / Router Portal</div><span class="eyebrow">ROUTER PORTAL · GUIDE MODE</span><h1>Enter the help portal for your network.</h1><p class="hero-lead">Tell Router Portal what is wrong. Start with a question, an IP address, a router brand, or a common Wi-Fi problem.</p>${searchBox()}<div class="entry-row"><a class="entry" href="${pageUrl('/router-login/')}">🔐 Router Login</a><a class="entry" href="${pageUrl('/router-login-not-working/')}">📶 Wi-Fi Issue</a><a class="entry" href="${pageUrl('/find-router-ip/')}">🌐 Find IP</a><a class="entry" href="${pageUrl('/router-login-not-working/')}">🛠️ Fix Connection</a></div></div><div class="portal-panel" aria-label="Network portal status"><div class="wave"></div><div class="status-line"><span class="online"><i></i> Portal ready</span><span>Help Center</span></div><div class="signal"><b></b><b></b><b></b><b></b></div><div class="portal-title">Your Router Help Zone</div><div class="portal-sub">A clear path from problem → diagnosis → solution</div><a class="enter" href="${pageUrl('/router-login-not-working/')}">Enter Problem Solver →</a></div></div></section>` : `<section class="page-hero"><div class="page-hero-inner"><div class="breadcrumbs"><a href="${pageUrl('/')}">Home</a> / Router help</div><span class="eyebrow">${page.label}</span><h1>${page.h1}</h1><p>${page.intro}</p></div></section>`;
  const utility = '';
  const main = page.home ? page.body : `<div class="article-shell"><article class="article"><aside class="toc"><b>ON THIS PAGE</b><a href="${pageUrl('/router-login/')}">Quick answer</a><a href="${pageUrl('/find-router-ip/')}">Find IP</a><a href="${pageUrl('/router-login-not-working/')}">Troubleshoot</a><a href="${pageUrl('/all-guides/')}">More guides</a></aside><div class="article-main"><div class="article-tags"><span class="tag">${page.label}</span><span class="tag">Router Portal guide</span></div>${page.body}</div></article></div>`;
  const isNoindex = page.noindex === true;
  const canonicalTag = isNoindex ? '' : `<link rel="canonical" href="${canonical(page.slug)}">`;
  const robotsTag = `<meta name="robots" content="${isNoindex ? 'noindex,follow' : 'index,follow'}">`;
  const socialTags = isNoindex ? '' : `<meta property="og:site_name" content="Router Portal"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:url" content="${canonical(page.slug)}"><meta property="og:type" content="website"><meta property="og:image" content="${canonical('/assets/logo-wifi.png')}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${description}"><meta name="twitter:image" content="${canonical('/assets/logo-wifi.png')}">`;
  const schema = isNoindex ? '' : (() => { const data = { '@context':'https://schema.org','@type':page.home?'WebSite':(page.schemaType || 'WebPage'),name:page.home?'Router Portal':title,url:canonical(page.slug),description }; if (page.home) data.publisher = { '@type':'Organization',name:'Router Portal',url:siteUrl,logo:{ '@type':'ImageObject',url:canonical('/assets/logo-wifi.png') } }; if (page.slug === '/about/') { data.mainEntity = { '@type':'Organization',name:'Router Portal',url:siteUrl,founder:{ '@type':'Person',name:'Md Juyel',jobTitle:'Founder and CEO',url:canonical('/about/') },foundingDate:'2026',areaServed:'Worldwide',logo:canonical('/assets/logo-wifi.png'),email:'routerportals@gmail.com',telephone:'+8801332369029',sameAs:['https://www.facebook.com/share/1G6Bz6U17h/'],contactPoint:{ '@type':'ContactPoint',contactType:'customer support',email:'routerportals@gmail.com',telephone:'+8801332369029',availableLanguage:['English'] } }; } if (!page.home) data.breadcrumb = {'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:canonical('/')},{'@type':'ListItem',position:2,name:page.label,item:canonical(page.slug)}]}; return `<script type="application/ld+json">${JSON.stringify(data)}</script>`; })();
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><meta name="author" content="Router Portal Editorial Team"><meta name="keywords" content="${escapeHtml((page.searchTerms || '').split(',').slice(0,8).join(', '))}"><meta name="theme-color" content="#2f6fed"><meta name="google-site-verification" content="iah_huluCmfWfZhIDsoW2YW1HP9HJmICG1rkl1VXRqk">${robotsTag}${canonicalTag}<link rel="icon" href="${pageUrl('/assets/favicon-wifi.png')}" type="image/png" sizes="64x64"><link rel="shortcut icon" href="${pageUrl('/assets/favicon-wifi.png')}" type="image/png"><link rel="apple-touch-icon" href="${pageUrl('/assets/favicon-wifi.png')}" sizes="64x64"><link rel="stylesheet" href="${pageUrl('/assets/style-v8.css')}">${socialTags}${schema}</head><body><a class="skip-link" href="#main">Skip to content</a>${header()}${hero}${utility}<div id="main">${main}</div>${bottomNav()}${footer()}<script src="${pageUrl('/assets/app-v2.js')}" defer></script></body></html>`;
}

await rm(dist, { recursive: true, force: true });
await mkdir(join(dist, 'assets'), { recursive: true });
await mkdir(join(dist, 'assets'), { recursive: true });
for (const asset of ['style-v8.css','logo-wifi.png','favicon-wifi.png','founder-md-juyel.jpg']) await copyFile(join(root,'public/assets',asset), join(dist,'assets',asset));
const searchIndex = pages.map(p => ({ title:p.h1, description:p.description, path:pageUrl(p.slug), keywords:[p.h1, p.label, p.searchTerms || '', p.slug.replaceAll('/',' ').replaceAll('-',' ')] }));
const qrLibrary = await readFile(join(root, 'node_modules/qrcode-generator/qrcode.js'), 'utf8');
const appJs = qrLibrary + `
(() => {
  const toggle = document.querySelector('.nav-toggle');
  const links = document.querySelector('.nav-links');
  if (toggle && links) {
    toggle.addEventListener('click', () => {
      const open = links.classList.toggle('open');
      toggle.setAttribute('aria-expanded', String(open));
    });
  }
  document.querySelectorAll('[data-copy-ip]').forEach(btn => btn.addEventListener('click', async () => { try { await navigator.clipboard.writeText(btn.dataset.copyIp); const old = btn.textContent; btn.textContent = 'Copied'; setTimeout(() => btn.textContent = old, 1200); } catch { btn.textContent = 'Copy manually'; } }));
  document.querySelectorAll('[data-copy-guide]').forEach(btn => btn.addEventListener('click', async () => { try { await navigator.clipboard.writeText(location.href); const old = btn.textContent; btn.textContent = 'Link copied'; setTimeout(() => btn.textContent = old, 1400); } catch { btn.textContent = 'Copy from address bar'; } }));
    const form = document.querySelector('#site-search');
  const input = document.querySelector('#search-input');
  const results = document.querySelector('#search-results');
  if (form && input && results) {
    let index = [];
    fetch('${pageUrl('/search-index.json')}').then(r => r.json()).then(x => { index = x; }).catch(() => {});
    const show = () => {
      const q = input.value.trim().toLowerCase();
      if (!q) { results.style.display = 'none'; results.innerHTML = ''; return; }
      const hits = index.filter(item => (item.title + ' ' + item.description + ' ' + item.keywords.join(' ')).toLowerCase().includes(q)).slice(0, 6);
      results.innerHTML = hits.length ? hits.map(x => '<a href="' + x.path + '"><strong>' + x.title + '</strong><small>' + x.description + '</small></a>').join('') : '<div style="padding:14px;color:#60708c">No matching guide yet. Try a common router IP.</div>';
      results.style.display = 'block';
    };
    input.addEventListener('input', show);
    form.addEventListener('submit', e => { e.preventDefault(); const first = results.querySelector('a'); if (first) location.href = first.href; else show(); });
  }
  const cidrBtn=document.querySelector('#cidr-button');
  if(cidrBtn){cidrBtn.addEventListener('click',()=>{const input=document.querySelector('#cidr-input').value.trim();const out=document.querySelector('#cidr-result');const parts=input.split('/');const octets=(parts[0]||'').split('.');const prefixText=parts[1]||'';const valid=octets.length===4&&octets.every(x=>/^[0-9]+$/.test(x)&&Number(x)<=255)&&/^[0-9]+$/.test(prefixText)&&Number(prefixText)<=32;const m=valid?[input,...octets,prefixText]:null;if(!m){out.textContent='Enter a valid IPv4 CIDR such as 192.168.1.0/24.';return;}const oct=m.slice(1,5).map(Number), prefix=Number(m[5]);if(oct.some(x=>x>255)){out.textContent='Each IPv4 octet must be between 0 and 255.';return;}const ip=(((oct[0]*256+oct[1])*256+oct[2])*256+oct[3])>>>0;const mask=prefix===0?0:(0xffffffff << (32-prefix))>>>0;const network=(ip&mask)>>>0;const broadcast=(network + (2**(32-prefix)-1))>>>0;const fmt=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255].join('.');const total=2**(32-prefix);const usable=prefix>=31? (prefix===32?1:2):Math.max(0,total-2);out.innerHTML='<strong>'+fmt(network)+'/'+prefix+'</strong><br>Mask: '+fmt(mask)+' · Network: '+fmt(network)+' · Broadcast: '+fmt(broadcast)+'<br>Range: '+fmt(prefix>=31?network:network+1)+' – '+fmt(prefix>=31?broadcast:broadcast-1)+' · Total: '+total+' · Conventional usable: '+usable;});}
  const qrBtn=document.querySelector('#wifi-qr-button');
  if(qrBtn){qrBtn.addEventListener('click',()=>{const ssid=document.querySelector('#wifi-ssid').value, pass=document.querySelector('#wifi-password').value, sec=document.querySelector('#wifi-security').value, hidden=document.querySelector('#wifi-hidden').checked?'true':'false', out=document.querySelector('#wifi-qr-preview');if(!ssid){out.textContent='Enter the network name first. Nothing is sent to Router Portal.';return;}const esc=x=>x.replace(/([\\;,:])/g,'\\$1');const payload='WIFI:T:'+sec+';S:'+esc(ssid)+';P:'+esc(pass)+';H:'+hidden+';;';const qr=qrcode(0,'M');qr.addData(payload);qr.make();out.innerHTML='<strong>Local Wi-Fi QR preview</strong><div class="qr-svg">'+qr.createSvgTag({scalable:true})+'</div><pre>'+payload.replace(/</g,'&lt;')+'</pre><small>Generated in this browser. The payload is not sent to Router Portal or a third-party API.</small>';});}
  const pingBtn=document.querySelector('#ping-button');
  if(pingBtn) pingBtn.addEventListener('click',()=>{document.querySelector('#ping-result').textContent='Measurement is not run by this static preview. Use a controlled, rate-limited probe with a disclosed method; do not enter an unauthorised target.';});
  const portBtn=document.querySelector('#port-check-button');
  if(portBtn) portBtn.addEventListener('click',()=>{const host=document.querySelector('#port-host').value.trim(), port=Number(document.querySelector('#port-number').value), out=document.querySelector('#port-result');out.textContent=host && port>=1 && port<=65535?'A production probe must verify one authorised target with a disclosed vantage point. This static build does not claim an open/closed result.':'Enter one valid authorised host and a port from 1 to 65535.';});
  const addressBtn=document.querySelector('#v2-address-button');
  if(addressBtn) addressBtn.addEventListener('click',()=>{const raw=document.querySelector('#v2-address-input').value.trim(),out=document.querySelector('#v2-address-result'),m=raw.match(/^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$/);if(!m){out.textContent='সঠিক IPv4 লিখুন, যেমন 192.168.1.1।';return;}const a=m.slice(1).map(Number),valid=a.every(n=>n>=0&&n<=255),private=(a[0]===10)||(a[0]===172&&a[1]>=16&&a[1]<=31)||(a[0]===192&&a[1]===168);if(!valid){out.textContent='প্রতিটি অংশ 0 থেকে 255-এর মধ্যে হতে হবে।';return;}out.innerHTML='<strong>'+raw+' বৈধ IPv4 address।</strong><br>'+ (private?'এটি private range-এর মধ্যে পড়ে।':'এটি private home-router range নয়।')+'<br><small>এটি আপনার gateway বা admin address প্রমাণ করে না; connected device-এর gateway যাচাই করুন।</small>';});
  document.querySelectorAll('[data-v2-decision]').forEach(btn=>btn.addEventListener('click',()=>{const out=document.querySelector('#v2-decision-result'),messages={slow:'প্রথমে gateway, cable, Wi‑Fi ও power-cycle পরীক্ষা করুন। Factory reset এখনই দরকার নেই।',password:'Model-specific recovery, label ও setup record দেখুন। Credential অনুমান করবেন না; reset শেষ বিকল্প।',config:'Backup থাকলে প্রস্তুত রাখুন। Exact model instructions দেখে শেষ বিকল্প হিসেবে factory reset বিবেচনা করুন।'};out.innerHTML='<strong>পরবর্তী নিরাপদ ধাপ:</strong> '+messages[btn.dataset.v2Decision];}));
  const v2Checks=[...document.querySelectorAll('[data-v2-check]')];
  if(v2Checks.length){const out=document.querySelector('#v2-check-result'),refresh=()=>{const done=v2Checks.filter(x=>x.checked).length; if(out) out.textContent=done+' / '+v2Checks.length+'টি item সম্পন্ন। পরিবর্তন করার আগে model ও ISP নির্দেশনা যাচাই করুন।';};v2Checks.forEach(x=>x.addEventListener('change',refresh));refresh();}
})();`;
await writeFile(join(dist, 'assets/app-v2.js'), appJs);
await writeFile(join(dist, 'search-index.json'), JSON.stringify(searchIndex, null, 2));
for (const page of pages) { const file = page.slug === '/' ? join(dist,'index.html') : join(dist,page.slug.replace(/^\//,'') ,'index.html'); await mkdir(dirname(file), {recursive:true}); await writeFile(file, layout(page)); }
  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${pages.map(p=>`  <url><loc>${canonical(p.slug)}</loc></url>`).join('\n')}\n</urlset>\n`;
  await writeFile(join(dist,'sitemap.xml'), sitemap);
  await writeFile(join(dist,'sitemap.txt'), `${pages.map(p=>canonical(p.slug)).join('\n')}\n`);
  await writeFile(join(dist,'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${canonical('/sitemap.xml')}\nSitemap: ${canonical('/sitemap.txt')}\n`);
  await writeFile(join(dist,'manus-routes.json'), JSON.stringify({routes:pages.map(p=>({path:pageUrl(p.slug),title:p.h1}))}, null, 2));
  await writeFile(join(dist,'404.html'), layout({slug:'/404.html',noindex:true,title:'Page Not Found | Router Portal',description:'The router guide page could not be found.',label:'Not found',h1:'That page is not here',intro:'Try a popular router login guide instead.',body:`<main class="content-layout"><article class="prose"><h2>Try a common guide</h2><p><a href="${pageUrl('/router-login/')}">Router admin login</a> or <a href="${pageUrl('/find-router-ip/')}">find your router IP</a>.</p></article></main>`}));
console.log(`Built ${pages.length} pages at ${dist}`);
