const safety = `<div class="notice"><strong>নিরাপত্তা সীমা:</strong> এই নির্দেশনা কেবল আপনার নিজের বা অনুমোদিত router/network-এর জন্য। Router Portal-এ কোনো router password, Wi‑Fi password, MAC, serial বা private network screenshot দেবেন না।</div>`;
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugLink = (pageUrl, path, label) => `<a href="${pageUrl(path)}">${label}</a>`;
const titleFor = (h1) => {
  const t = `${h1} | Router Portal`;
  if (t.length <= 60) return t;
  const short = h1.split(':')[0].trim();
  const t2 = `${short} | Router Portal`;
  return t2.length <= 60 ? t2 : `${short.slice(0, 42).trim()} | Router Portal`;
};
const visual = (kind, label, nodes) => {
  const cls = kind === 'topology' ? 'topology-visual' : kind === 'compare' ? 'compare-visual' : kind === 'check' ? 'check-visual' : 'flow-visual';
  return `<figure class="router-visual ${cls}" role="img" aria-label="${esc(label)}"><div class="console-bar"><span class="console-dot"></span><span>${esc(label)}</span><code>ROUTER PORTAL / SAFE MODE</code></div><div class="visual-nodes">${nodes.map((n,i)=>`<div class="visual-node"><b>${i+1}</b><span>${esc(n)}</span></div>`).join('<i aria-hidden="true">→</i>')}</div><figcaption>${esc(label)} — original Router Portal visual; values are examples, not a guarantee for every model.</figcaption></figure>`;
};
const table = (rows) => `<div class="responsive-table"><table><thead><tr><th>যা দেখবেন</th><th>এর অর্থ</th><th>নিরাপদ next step</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`;
const specs = [
['/gateway/find-router-ip-windows-11/','Windows 11-এ router IP খোঁজা','find router IP Windows 11','Command Prompt-এ `ipconfig` চালিয়ে active Wi‑Fi/Ethernet adapter-এর Default Gateway কপি করুন।',['Open Command Prompt','Run ipconfig','Find Default Gateway','Open the address bar'],[['Adapter output','Wi‑Fi ও Ethernet-এর gateway আলাদা হতে পারে','যে connection ব্যবহার করছেন সেটিই নিন'],['VPN output','VPN route misleading হতে পারে','VPN/proxy সাময়িকভাবে check করুন'],['No gateway','Connection আসেনি বা adapter inactive','Wi‑Fi/Ethernet status ঠিক করুন']],'/find-router-ip/; /router-login/; /router-login-not-working/','flow','P0'],
['/gateway/find-router-ip-macos/','macOS-এ router IP খোঁজা','find router IP Mac','Wi‑Fi Details-এর Router field অথবা Terminal-এর `route get default` দিয়ে current gateway দেখুন।',['Open System Settings','Choose connected network','Read Router value','Open local address'],[['Settings path','macOS version অনুযায়ী label বদলায়','Router field বা route output মিলিয়ে নিন'],['Ethernet','Wi‑Fi-এর মতোই আলাদা interface হতে পারে','active interface নির্বাচন করুন'],['No value','Network connected নয়','Reconnect before troubleshooting']],'/find-router-ip/; /router-login/; /gateway/router-login-by-hostname/','flow','P0'],
['/gateway/find-router-ip-android/','Android-এ default gateway খোঁজা','find router IP Android','Connected Wi‑Fi-এর Details/Advanced অংশে Gateway বা Router value দেখুন।',['Open Wi‑Fi settings','Tap connected network','Read Gateway/Router','Copy without sharing'],[['OEM labels','Pixel/Samsung/other UI আলাদা','version-specific label note করুন'],['Mobile data','Cellular data home gateway দেখায় না','home Wi‑Fi-তে connect করুন'],['Third-party app','সবসময় প্রয়োজন নেই','built-in details আগে ব্যবহার করুন']],'/find-router-ip/; /router-login/; /router-login-not-working/','flow','P0'],
['/gateway/find-router-ip-iphone-ipad/','iPhone/iPad-এ router address খোঁজা','find router IP iPhone','Settings → Wi‑Fi → connected network-এর info panel-এ Router field কপি করুন।',['Open Settings','Tap Wi‑Fi','Tap connected network','Read Router field'],[['Cellular-only','Cellular data-তে local gateway নেই','same Wi‑Fi network ব্যবহার করুন'],['Private Relay','এটি router login address নয়','local Router field ব্যবহার করুন'],['iPad','iPhone-এর মতো একই concept','OS label versionভেদে মিলিয়ে নিন']],'/find-router-ip/; /router-login/; /router-login-not-working/','flow','P0'],
['/gateway/find-router-ip-linux/','Linux-এ default gateway খোঁজা','find router IP Linux','Terminal-এ `ip route` চালিয়ে `default via`-এর address শনাক্ত করুন।',['Open Terminal','Run ip route','Read default via','Open browser address bar'],[['Modern command','`ip route` current route দেখায়','পুরনো command-এর বদলে এটি ব্যবহার করুন'],['NetworkManager','`nmcli device show` সহায়ক','active device-এর gateway নিন'],['No route','Network connection নেই','interface reconnect করুন']],'/find-router-ip/; /router-login/; /gateway/192-168-vs-10-private-ip/','flow','P0'],
['/gateway/192-168-vs-10-private-ip/','192.168.x.x বনাম 10.x.x.x private IP','192.168 vs 10 private IP','দুটিই private range; router login-এর জন্য আপনার device-এর current Default Gateway-ই সঠিক প্রমাণ।',['Identify private range','Read current gateway','Avoid public-IP confusion','Open local admin page'],[['192.168.0.0/16','Home LAN-এ খুব common','address alone দিয়ে model অনুমান নয়'],['10.0.0.0/8','ISP/gateway-এও দেখা যায়','10.0.0.1 universal নয়'],['100.64.0.0/10','CGNAT context হতে পারে','WAN/public distinction দেখুন']],'/find-router-ip/; /tools/what-is-my-ip/; /network/cgnat-explained/','compare','P0'],
['/gateway/router-login-by-hostname/','Router hostname দিয়ে login','router login by hostname','কিছু model IP-এর বদলে `routerlogin.net`, `tplinkwifi.net` বা local hostname ব্যবহার করে; official source দিয়ে মিলিয়ে নিন।',['Read model label','Find documented hostname','Stay on local network','Verify certificate/URL'],[['Hostname','Model-specific local name','manual/support page মিলান'],['DNS failure','Hostname resolve নাও করতে পারে','current gateway ব্যবহার করুন'],['Public lookalike','Internet site local admin নয়','address bar ও local connection যাচাই করুন']],'/router-model-login/; /find-router-ip/; /models/router-manuals-and-support/','flow','P1'],
['/gateway/ipv6-router-login/','IPv6 দিয়ে router admin page খোলা','IPv6 router login','IPv6 gateway বা link-local address ব্যবহার করলে interface zone এবং exact model documentation প্রয়োজন হতে পারে।',['Check IPv6 gateway','Confirm local link','Use documented bracket syntax','Verify router page'],[['Link-local','`fe80::` interface-specific','zone identifier প্রয়োজন হতে পারে'],['IPv6 disabled','সব router একইভাবে চালায় না','IPv4 gateway fallback নিন'],['Admin exposure','WAN IPv6 access আলাদা বিষয়','remote management enable করবেন না']],'/find-router-ip/; /network/ipv6-home-router-basics/; /security/remote-management-risk/','topology','P1'],
['/models/how-to-identify-router-model/','Router model ও hardware revision শনাক্ত করা','identify router model','Label-এর model code, hardware revision ও ISP branding মিলিয়ে exact device record তৈরি করুন।',['Photograph label privately','Read model code','Read hardware revision','Check official support'],[['Model code','Marketing family নয়, exact code','support page-এ exact match নিন'],['Revision','A1/V2/Ver.3 instruction বদলাতে পারে','revision বাদ দিয়ে guide প্রয়োগ নয়'],['ISP label','Provider firmware হতে পারে','ISP support path আলাদা রাখুন']],'/router-model-login/; /models/hardware-revision/; /models/router-manuals-and-support/','check','P0'],
['/models/hardware-revision/','Hardware revision কেন login নির্দেশনা বদলায়','router hardware revision','একই product name-এর revision-এ firmware, menu, reset ও default state আলাদা হতে পারে।',['Locate revision','Match manual','Check firmware family','Use exact steps'],[['Revision label','V1/V2/A1 fields গুরুত্বপূর্ণ','model page-এ রাখুন'],['Firmware','ISP build আলাদা হতে পারে','official update notes দেখুন'],['Reset hole','timing model-specific','random timing এড়ান']],'/models/how-to-identify-router-model/; /models/firmware-isp-variants/; /factory-reset-router/','compare','P0'],
['/models/router-login-evidence-card/','Verified router evidence card কীভাবে পড়বেন','router login evidence card','একটি evidence card-এ model, revision, login address, credential status, source ও last-checked date একসঙ্গে দেখুন।',['Match exact model','Read credential status','Open source','Check date'],[['Address','সম্ভাব্য local URL','current gateway দিয়ে confirm'],['Credential status','factory/label/setup/unknown','universal password ধরে নেবেন না'],['Source/date','evidence freshness','firmware change হলে recheck']],'/router-model-login/; /default-router-passwords/; /models/router-manuals-and-support/','check','P0'],
['/isp/router-login-by-isp/','ISP অনুযায়ী router login প্রস্তুতি','router login by ISP','ISP-provided gateway-এ admin access, app control, bridge mode ও support boundary providerভেদে বদলায়।',['Identify provider','Identify supplied device','Check app/manual','Protect account'],[['Provider firmware','Generic brand steps নাও মিলতে পারে','ISP guide আগে দেখুন'],['Managed access','Admin UI বন্ধ থাকতে পারে','support/official app ব্যবহার করুন'],['Own router','ISP modem/router আলাদা','topology লিখে নিন']],'/isp/isp-router-admin-access/; /models/firmware-isp-variants/; /gateway/find-router-ip-windows-11/','topology','P0'],
['/isp/isp-router-admin-access/','ISP router বনাম নিজের router admin access','ISP router admin access','ISP gateway, bridge modem ও নিজের router-এর boundary বুঝে কোন device-এ login করবেন ঠিক করুন।',['Draw topology','Find each gateway','Check provider policy','Choose safe admin path'],[['Single gateway','একটি router control করে','current gateway খুলুন'],['Modem + router','double NAT হতে পারে','upstream/downstream আলাদা করুন'],['Managed device','credentials provider-controlled','reset নয়, provider path নিন']],'/network/double-nat-diagnosis/; /network/bridge-mode-vs-ap-mode/; /isp/router-login-by-isp/','topology','P0'],
['/models/firmware-isp-variants/','Firmware ও ISP variant login differences','router firmware ISP variant','একই model-এর retail ও ISP firmware-এ menu, hostname, credentials ও update policy আলাদা হতে পারে।',['Read firmware label','Match region/ISP','Open release notes','Choose correct manual'],[['Retail firmware','manufacturer menu','official support match করুন'],['ISP firmware','custom UI/access','provider support priority'],['Region','channel/power/menu বদলাতে পারে','region-specific source নিন']],'/models/hardware-revision/; /security/firmware-update-safety/; /isp/router-login-by-isp/','compare','P0'],
['/models/router-manuals-and-support/','Router manual ও official support খোঁজা','router manual support','Exact model ও revision দিয়ে manufacturer/ISP-এর official manual, firmware এবং support page খুঁজুন।',['Read exact model','Open official domain','Check revision','Save source date'],[['Manual','PDF বা web guide','copyright/URL রাখুন'],['Firmware','release note জরুরি','wrong region flash নয়'],['Support','ISP case আলাদা','official escalation করুন']],'/models/how-to-identify-router-model/; /models/firmware-isp-variants/; /editorial-policy/','check','P0'],
['/brand-router-model-search/','Brand/model search ও verified index','router brand model search','Brand → model → revision → source flow ব্যবহার করুন; empty বা unsupported result index করবেন না।',['Choose brand','Search exact model','Read evidence status','Open source'],[['Brand page','discovery hub মাত্র','model proof ছাড়া credential নয়'],['No result','unsupported state','thin doorway page নয়'],['Verified result','source/date সহ','related task খুলুন']],'/router-model-login/; /default-router-passwords/; /models/router-login-evidence-card/','flow','P0'],
['/security/after-router-login-checklist/','Login করার পর router security checklist','router security checklist','Login করার পরে admin password, firmware, remote management, UPnP, Wi‑Fi ও backup review করুন।',['Change admin credential','Update firmware','Review remote access','Backup safely'],[['Admin','unique passphrase','private password manager'],['Remote access','attack surface','প্রয়োজন না হলে off'],['Backup','settings recovery','credential export নয়']],'/change-router-admin-password/; /security/firmware-update-safety/; /security/remote-management-risk/','check','P0'],
['/security/router-admin-account-types/','Router admin account ও credential states','router admin account types','Factory default, label-generated, setup-created, ISP-managed ও unknown state আলাদা করে বুঝুন।',['Identify account state','Check model/revision','Avoid guessing','Create safe credential'],[['Factory','documented starting value','first login-এ change'],['Label-generated','unit-specific','label privately read'],['ISP-managed','provider controlled','official support']],'/default-router-passwords/; /change-router-admin-password/; /isp/isp-router-admin-access/','compare','P0'],
['/security/firmware-update-safety/','Router firmware update নিরাপদে করা','safe router firmware update','Backup, exact revision/region, power stability ও official release note check না করে firmware update করবেন না।',['Read release notes','Backup configuration','Match revision/region','Update and verify'],[['Wrong image','router unusable হতে পারে','exact support page match'],['Power loss','update corrupt হতে পারে','stable power ব্যবহার'],['After update','settings/menu বদলাতে পারে','login/Wi‑Fi verify']],'/models/firmware-isp-variants/; /models/router-manuals-and-support/; /security/firmware-end-of-life/','check','P0'],
['/security/firmware-end-of-life/','Router firmware end-of-life ও replacement','router firmware end of life','Security updates বন্ধ হলে exposure, support, ISP compatibility ও replacement cost একসঙ্গে বিচার করুন।',['Check last update','Check vendor notice','Assess exposure','Plan replacement'],[['EOL','নতুন patch নেই','remote features বন্ধ/replacement'],['Unsupported ISP','replacement আগে provider check','bridge/AP option ভাবুন'],['Old hardware','performance নয়, security risk','data-backed decision']],'/security/firmware-update-safety/; /reviews/router-for-apartment/; /reviews/router-for-home-server/','compare','P1'],
['/security/remote-management-risk/','Remote router administration-এর ঝুঁকি','router remote management risk','WAN-side admin access প্রয়োজন না হলে বন্ধ রাখুন; local admin ও secure VPN/relay-এর পার্থক্য বুঝুন।',['Find remote admin setting','Check allowed source','Disable if unnecessary','Verify locally'],[['WAN admin','Internet-facing login','off বা restricted'],['Cloud app','vendor account path','MFA/privacy review'],['VPN','safer remote route','official method follow']],'/security/after-router-login-checklist/; /network/dmz-vs-port-forwarding/; /security/router-firewall-basics/','topology','P0'],
['/security/upnp-explained/','UPnP কী এবং নিরাপদে review করা','UPnP router security','UPnP convenience ও automatic port mapping-এর সুবিধা/ঝুঁকি বুঝে device need অনুযায়ী review করুন।',['List dependent devices','Inspect mappings','Choose policy','Recheck apps'],[['Automatic mapping','manual work কম','unexpected exposure review'],['IoT','trust boundary weak হতে পারে','segmentation ভাবুন'],['Disable','কিছু app ভাঙতে পারে','specific alternative test']],'/port-forwarding/; /security/guest-network-vs-iot-network/; /security/after-router-login-checklist/','compare','P1'],
['/security/wps-security/','WPS security ও বন্ধ করার সিদ্ধান্ত','WPS security router','WPS-এর push-button/PIN behavior, convenience ও risk model বুঝে প্রয়োজন অনুযায়ী disable করুন।',['Identify WPS mode','Check client needs','Disable PIN if possible','Verify Wi‑Fi'],[['PIN','অনেক ক্ষেত্রে weaker path','disable/review'],['Push button','short pairing window','physical control রাখুন'],['Legacy client','compatibility issue','newer secure setup']],'/security/after-router-login-checklist/; /wifi/wpa2-vs-wpa3/; /wifi/wifi-password-sharing-safely/','compare','P1'],
['/security/guest-network-vs-iot-network/','Guest network বনাম IoT network','guest network vs IoT','Guest isolation ও IoT segmentation একই জিনিস নয়; router feature ও device trust অনুযায়ী policy করুন।',['Inventory devices','Enable guest isolation','Separate IoT','Test local access'],[['Guest','visitor internet access','LAN isolation check'],['IoT','untrusted device group','dedicated SSID/VLAN'],['Printer/NAS','local access need','exception document']],'/security/router-firewall-basics/; /wifi/wpa2-vs-wpa3/; /network/bridge-mode-vs-ap-mode/','topology','P1'],
['/security/router-firewall-basics/','Router firewall basics ও verification','router firewall basics','Firewall enabled আছে কি না, inbound rules, IPv6 policy ও port forwarding-এর interaction review করুন।',['Check firewall state','Review inbound rules','Review IPv6','Test approved service'],[['Default firewall','stateful filtering','default রাখা সহায়ক'],['Inbound rule','specific exposure','least privilege'],['IPv6','separate policy হতে পারে','IPv6 firewall verify']],'/security/remote-management-risk/; /network/ipv6-home-router-basics/; /port-forwarding/','check','P1'],
['/security/hacked-router-triage/','Router compromise সন্দেহ হলে triage','hacked router what to do','অস্বাভাবিক DNS, unknown admin change বা redirect দেখলে evidence preserve, isolate ও official recovery path নিন।',['Record symptoms','Disconnect risky access','Change credentials safely','Check firmware/ISP'],[['DNS redirect','resolver setting inspect','device/browser also check'],['Unknown admin','account state review','provider/vendor escalate'],['Evidence','reset করলে হারাতে পারে','notes রাখুন, secret নয়']],'/security/after-router-login-checklist/; /security/firmware-update-safety/; /network/dns-settings-router/','check','P1'],
['/wifi/slow-wifi-diagnosis/','Slow Wi-Fi diagnosis: layered flow','slow Wi-Fi diagnosis','Wired বনাম Wi‑Fi, gateway latency, distance, interference, client load ও ISP speed আলাদা করে পরীক্ষা করুন।',['Test wired baseline','Test near router','Test far room','Compare time/load'],[['Wired fast','wireless layer issue','channel/placement review'],['Both slow','WAN/ISP or router load','public test caveat'],['One device','client issue','driver/power settings']],'/tools/ping-test/; /wifi/channel-interference/; /wifi/bufferbloat-and-latency/','flow','P0'],
['/wifi/frequent-disconnects/','Wi-Fi বারবার disconnect হলে কী পরীক্ষা করবেন','Wi-Fi disconnect troubleshooting','SSID band steering, signal, power saving, firmware, DHCP lease ও interference ক্রমে পরীক্ষা করুন।',['Observe pattern','Check signal/band','Update client/router','Review DHCP'],[['All devices','router/AP issue','logs/firmware check'],['One device','client issue','forget/rejoin/update'],['Only one band','channel/compatibility','band setting compare']],'/wifi/slow-wifi-diagnosis/; /security/firmware-update-safety/; /network/dhcp-reservation-vs-static-ip/','flow','P0'],
['/wifi/channel-interference/','Wi-Fi channel ও interference নির্বাচন','best Wi-Fi channel','2.4GHz channel overlap, 5GHz DFS/region behavior ও apartment interference দেখে channel choose করুন।',['Identify crowded band','Check channel width','Choose allowed channel','Retest latency'],[['2.4GHz','overlap বেশি','20MHz often safer'],['5GHz','DFS/region caveat','device support check'],['Width','wider is not always faster','stability first']],'/wifi/2-4ghz-vs-5ghz-vs-6ghz/; /wifi/slow-wifi-diagnosis/; /reviews/router-for-apartment/','compare','P1'],
['/wifi/2-4ghz-vs-5ghz-vs-6ghz/','2.4GHz বনাম 5GHz বনাম 6GHz','2.4 5 6 GHz Wi-Fi','Band choice range, interference, device support, channel width ও backhaul-এর trade-off।',['List client support','Map room distance','Choose band policy','Retest'],[['2.4GHz','range/wall penetration','lower throughput'],['5GHz','capacity/latency','shorter range'],['6GHz','newer clients','region/device support']],'/wifi/channel-interference/; /wifi/wpa2-vs-wpa3/; /reviews/wifi-extenders-and-mesh/','compare','P0'],
['/wifi/wpa2-vs-wpa3/','WPA2 বনাম WPA3: কোন Wi-Fi security','WPA2 vs WPA3','WPA3 security benefit, client compatibility, transition mode ও password hygiene একসঙ্গে বিচার করুন।',['Check client support','Choose mode','Set strong key','Reconnect devices'],[['WPA3','newer protection','client support required'],['WPA2','legacy compatibility','AES preferred'],['Transition','mixed clients','upgrade plan রাখুন']],'/security/wps-security/; /wifi/wifi-password-sharing-safely/; /security/after-router-login-checklist/','compare','P0'],
['/wifi/ssid-change-checklist/','SSID বদলানোর আগে ও পরে checklist','change Wi-Fi SSID','SSID change-এর আগে devices, IoT, mesh nodes ও saved networks-এর impact plan করুন।',['Record current setup','Choose neutral SSID','Save settings','Reconnect clients'],[['SSID name','network identity বদলায়','personal info নয়'],['Mesh','nodes sync দরকার','same controller path'],['IoT','reconnect cost','inventory আগে করুন']],'/change-wifi-password/; /wifi/wifi-password-sharing-safely/; /wifi/wpa2-vs-wpa3/','check','P1'],
['/wifi/wifi-password-sharing-safely/','Wi-Fi password/QR নিরাপদে share করা','share Wi-Fi password safely','QR ও password bearer credential; guest network, expiry/rotation ও private sharing বিবেচনা করুন।',['Choose guest or main','Generate locally','Share privately','Rotate when needed'],[['QR','image থাকলেই access','public post নয়'],['Guest','LAN isolation','IoT/NAS access test'],['Rotation','old shares expire','devices reconnect']],'/tools/wifi-qr-code/; /security/guest-network-vs-iot-network/; /change-wifi-password/','check','P1'],
['/wifi/bufferbloat-and-latency/','Bufferbloat ও gaming latency','bufferbloat gaming latency','Bandwidth speed-এর চেয়ে queue delay, upload saturation, QoS/SQM ও wired baseline গুরুত্বপূর্ণ হতে পারে।',['Measure idle latency','Load upload/download','Compare queue delay','Tune QoS/SQM'],[['Idle ping','baseline','gateway vs internet compare'],['Loaded ping','queue growth','upload cap/SQM'],['Gaming client','Wi‑Fi variability','wired/control test']],'/tools/ping-test/; /wifi/slow-wifi-diagnosis/; /reviews/best-wifi-routers-for-gaming/','compare','P1'],
['/network/dhcp-reservation-vs-static-ip/','DHCP reservation বনাম static IP','DHCP reservation vs static IP','Router-managed reservation সাধারণত device address stable রাখে; manual static config-এর trade-off বুঝুন।',['Identify device','Record MAC privately','Reserve address','Reconnect and verify'],[['Reservation','router assigns fixed lease','LAN conflict কম'],['Static IP','device-side setting','gateway/DNS mismatch risk'],['Server','stable target দরকার','document rollback']],'/port-forwarding/; /tools/port-forwarding-worksheet/; /network/double-nat-diagnosis/','compare','P0'],
['/network/dns-settings-router/','Router DNS settings: choice ও troubleshooting','router DNS settings','DNS resolver change-এর আগে ISP behavior, DoH/DoT, IPv6 DNS, fallback ও privacy effect বুঝুন।',['Record current DNS','Choose documented resolver','Apply carefully','Test resolution'],[['ISP DNS','support/integration','default may be valid'],['Public DNS','alternative resolver','privacy/latency varies'],['IPv6 DNS','separate path','both stacks test']],'/tools/dns-leak-router-check/; /security/hacked-router-triage/; /network/ipv6-home-router-basics/','check','P0'],
['/network/bridge-mode-vs-ap-mode/','Bridge mode বনাম access point mode','bridge mode vs access point','Bridge modem routing বন্ধ করে; AP mode secondary router-এর Wi‑Fi/LAN role বদলায়—topology আগে আঁকুন।',['Draw current topology','Identify routing device','Choose bridge or AP','Verify gateway'],[['Bridge','upstream router routes','ISP support may matter'],['AP','main router still routes','DHCP off/managed'],['Double NAT','two routers route','mode change can fix']],'/isp/isp-router-admin-access/; /network/double-nat-diagnosis/; /network/repeater-vs-access-point/','topology','P0'],
['/network/repeater-vs-access-point/','Repeater, mesh ও access point-এর পার্থক্য','repeater vs access point','Backhaul, latency, roaming, Ethernet availability ও placement দেখে extender/repeater/AP/mesh বাছুন।',['Check Ethernet','Map coverage','Choose backhaul','Retest room'],[['Repeater','wireless backhaul','capacity/latency cost'],['AP','wired backhaul','stable and predictable'],['Mesh','roaming/controller','node placement matters']],'/reviews/wifi-extenders-and-mesh/; /wifi/slow-wifi-diagnosis/; /wifi/channel-interference/','compare','P1'],
['/network/double-nat-diagnosis/','Double NAT শনাক্ত ও ঠিক করা','double NAT diagnosis','দুটি router routing করলে inbound access, gaming, discovery ও port forwarding জটিল হতে পারে।',['Compare WAN/LAN ranges','Trace gateway chain','Choose bridge/AP','Retest service'],[['Two private ranges','possible double NAT','upstream/downstream map'],['ISP gateway','managed device','bridge/AP policy check'],['Port failure','not always double NAT','CGNAT also test']],'/isp/isp-router-admin-access/; /network/bridge-mode-vs-ap-mode/; /network/cgnat-explained/','topology','P0'],
['/network/cgnat-explained/','CGNAT কী এবং port forwarding কেন ব্যর্থ','CGNAT port forwarding','WAN address private/shared হলে inbound forwarding নাও কাজ করতে পারে; ISP/IPv6/relay alternatives বুঝুন।',['Compare router WAN','Compare public IP','Check ISP terms','Choose alternative'],[['Private WAN','CGNAT likely','ISP request/public option'],['Shared public IP','inbound blocked','relay/VPN alternative'],['IPv6','different exposure model','firewall first']],'/port-forwarding/; /network/ipv6-home-router-basics/; /tools/local-vs-public-ip-check/','topology','P0'],
['/network/ipv6-home-router-basics/','Home router-এ IPv6 basics','IPv6 home router','IPv6 address, prefix delegation, firewall, SLAAC/DHCPv6 ও router admin access আলাদা বিষয়।',['Check ISP IPv6','Read prefix','Review firewall','Test client'],[['Global address','internet-routable হতে পারে','inbound firewall verify'],['ULA','private-like local range','not public reachability'],['Prefix delegation','ISP changes prefix','avoid hard-coded rules']],'/gateway/ipv6-router-login/; /security/router-firewall-basics/; /network/cgnat-explained/','topology','P1'],
['/network/mtu-mss-home-network/','MTU ও MSS: home-network troubleshooting','MTU MSS troubleshooting','Fragmentation, VPN/PPPoE path ও MSS clamping-এর সম্পর্ক বুঝে packet-size issue isolate করুন।',['Observe symptom','Test path','Check WAN type','Change only documented setting'],[['MTU','maximum frame payload','path-specific value'],['MSS','TCP segment hint','TCP-only context'],['VPN/PPPoE','overhead added','provider documentation']],'/network/dns-settings-router/; /wifi/slow-wifi-diagnosis/; /gateway/ipv6-router-login/','compare','P1'],
['/network/port-forwarding-vs-port-triggering/','Port forwarding বনাম port triggering','port forwarding vs triggering','Static inbound mapping ও outbound-triggered temporary mapping কোন use-case-এ মানায় তা বুঝুন।',['Identify service','Check vendor docs','Choose mapping','Test and cleanup'],[['Forwarding','always mapped','exposure remains'],['Triggering','outbound event opens','support varies'],['No mapping','relay/outbound app','safer when supported']],'/port-forwarding/; /tools/port-forwarding-worksheet/; /network/cgnat-explained/','compare','P1'],
['/network/dmz-vs-port-forwarding/','DMZ host বনাম নির্দিষ্ট port forwarding','DMZ vs port forwarding','DMZ broadly exposes a host; least-privilege specific forwarding সাধারণত safer starting point।',['Identify requirement','Check service ports','Use specific rule','Remove after use'],[['DMZ','broad exposure','avoid as default'],['Specific port','narrow exposure','service documentation'],['CGNAT','DMZ cannot bypass','check WAN path']],'/port-forwarding/; /security/router-firewall-basics/; /tools/port-forwarding-worksheet/','compare','P0'],
['/tools/gateway-self-check/','Gateway self-check worksheet','default gateway checker','Device, interface, gateway, browser result ও next action লিখে safe local-access worksheet পূরণ করুন।',['Record interface','Record gateway','Open address','Record result'],[['Interface','Wi‑Fi/Ethernet/VPN','active path নির্বাচন'],['Gateway','local next hop','public IP নয়'],['Result','login/timeout/refused','next branch নিন']],'/find-router-ip/; /router-login-not-working/; /gateway/192-168-vs-10-private-ip/','check','P0'],
['/tools/local-vs-public-ip-check/','Local IP বনাম public IP comparison tool','local IP vs public IP','Local/private address, router WAN ও observed public IP এক নয়; CGNAT-এ mismatch normal হতে পারে।',['Read local address','Read gateway','Observe public IP','Compare cautiously'],[['Local IP','LAN device identity','not internet-facing'],['Gateway','router next hop','admin path হতে পারে'],['Public IP','ISP/VPN-facing','sensitive context']],'/tools/what-is-my-ip/; /find-router-ip/; /network/cgnat-explained/','compare','P0'],
['/tools/dns-leak-router-check/','Router DNS leak self-check','router DNS leak check','Expected resolver ও observed DNS path তুলনা করুন; VPN/DoH/IPv6 আলাদা test না করলে result অসম্পূর্ণ।',['Choose expected resolver','Run controlled test','Compare IPv4/IPv6','Interpret limits'],[['Resolver','query endpoint','ownership/geolocation uncertain'],['VPN','path may intentionally differ','VPN policy read'],['DoH','browser bypass','router-only conclusion নয়']],'/network/dns-settings-router/; /security/after-router-login-checklist/; /network/ipv6-home-router-basics/','topology','P2'],
['/tools/port-forwarding-worksheet/','Port-forwarding rule worksheet','port forwarding worksheet','Service, listener, reserved LAN IP, protocol, source restriction, test method ও cleanup date লিখুন।',['Name service','Reserve host','Set least privilege','Test and cleanup'],[['Listener','service actually running','host firewall check'],['Rule','TCP/UDP/ports','vendor docs match'],['Cleanup','temporary exposure','disable/delete date']],'/port-forwarding/; /network/dhcp-reservation-vs-static-ip/; /network/cgnat-explained/','check','P0'],
['/reviews/router-for-apartment/','ছোট apartment-এর জন্য router নির্বাচন','best router for apartment','Floor area, wall density, ISP speed, client mix ও Ethernet availability আগে মাপুন; “best” claim নয়, evidence table ব্যবহার করুন।',['Map apartment','Count clients','Check ISP speed','Compare tested evidence'],[['Coverage','walls/placement matter','floor-plan test'],['Band','interference varies','2.4/5/6 support'],['Mesh','not always needed','wired AP alternative']],'/wifi/2-4ghz-vs-5ghz-vs-6ghz/; /network/repeater-vs-access-point/; /wifi/slow-wifi-diagnosis/','compare','P1'],
['/reviews/router-for-home-server/','Home server/NAS-এর জন্য router নির্বাচন','best router for home server','Stable DHCP reservations, firewall/IPv6 policy, backup ও remote-access alternatives দেখুন; শুধু port count নয়।',['Define service','Assess exposure','Check CGNAT/IPv6','Compare firmware support'],[['NAS','local access first','backup and least privilege'],['Remote access','forwarding risk','VPN/relay alternative'],['Firmware','long support matters','last update date']],'/port-forwarding/; /network/dhcp-reservation-vs-static-ip/; /network/cgnat-explained/; /security/router-firewall-basics/','topology','P1']
];
export function makeFiftyPages(pageUrl){
  return specs.map((r)=>{
    const [slug,h1,primary,quick,steps,rows,related,visualKind,priority]=r;
    const relatedLinks=related.split(';').map(x=>{const [p,label]=x.trim().split('|'); return slugLink(pageUrl,p,label||p);}).join(' · ');
    const keywords=`${primary}, Router Portal, router guide, ${h1}`;
    const description=`${quick} নিরাপদ ধাপ, সীমাবদ্ধতা, internal links এবং source-aware router guidance সহ।`;
    const topic = h1.includes('security')||h1.includes('WPS')||h1.includes('UPnP')||h1.includes('firmware')||h1.includes('compromise')?'Security & maintenance':h1.includes('Wi-Fi')||h1.includes('GHz')||h1.includes('SSID')||h1.includes('WPA')||h1.includes('bufferbloat')?'Wi-Fi performance':h1.includes('router IP')||h1.includes('gateway')||h1.includes('hostname')||h1.includes('IPv6 দিয়ে')?'Gateway & local access':h1.includes('router model')||h1.includes('hardware')||h1.includes('ISP')||h1.includes('manual')||h1.includes('evidence')||h1.includes('Brand')?'Models, brands & ISP':h1.includes('নির্বাচন')?'Buying guide':h1.includes('tool')||h1.includes('worksheet')||h1.includes('IP বনাম')||h1.includes('self-check')?'Tools & worksheets':'Network architecture';
    const faqItems=[
      [`${h1}-এ কি একই rule সব router-এ কাজ করবে?`,`না। Model, hardware revision, firmware, ISP, region এবং previous setup অনুযায়ী menu বা result বদলাতে পারে। Exact source ও current gateway মিলিয়ে নিন।`],
      ['Router Portal কি আমার credentials দেখতে পায়?','না। এই page কোনো router বা Wi‑Fi password চাইবে না; local admin page শুধু আপনার নিজের browser/network-এ খুলবে।'],
      ['কাজ না করলে প্রথম next step কী?','Connection, current Default Gateway, model/revision এবং official manual একসঙ্গে যাচাই করুন। Factory reset বা broad exposure প্রথম পদক্ষেপ নয়।']
    ];
    const body=`${safety}<div class="admin-console"><div><span class="status-pill">${priority} · ${topic}</span><span class="status-pill muted">SOURCE-AWARE GUIDE</span></div><strong>ROUTER PORTAL / ${esc(primary).toUpperCase()}</strong><small>Model, revision, ISP ও firmware scope আগে মিলিয়ে নিন</small></div><div class="answer-lead"><strong>উপরে থাকা মূল উত্তর:</strong> ${quick}</div>${visual(visualKind,`${h1} safe workflow`,steps)}<h2>এই page কেন useful</h2><p>${quick} ${h1} query-তে সাধারণ ভুল হলো popular address বা password-কে universal ধরে নেওয়া। এই guide-এ decision point, evidence status এবং stop condition আলাদা রাখা হয়েছে যাতে একই তথ্য অকারণে বারবার না আসে।</p><h2>কাজের ধাপ</h2><ol>${steps.map(s=>`<li>${s}</li>`).join('')}</ol><h2>Router-admin style decision panel</h2>${table(rows)}<h2>Verification ও সীমাবদ্ধতা</h2><p>Result বা instruction প্রকাশের আগে exact model/revision, firmware/ISP scope, official manual বা standards source এবং last-reviewed date মিলিয়ে নিন। Unknown হলে <strong>not verified</strong> লিখুন; অনুমানকে verified credential বা guaranteed fix হিসেবে দেখাবেন না।</p><h2>পরবর্তী useful links</h2><p>${relatedLinks}</p>${faq(faqItems)}<h2>Source ও review note</h2><p>এই page-এ manufacturer/ISP documentation, IETF/IANA/CISA বা relevant OS documentation-এর মতো source ব্যবহার করতে হবে। Page-এ Author, Reviewer, Last reviewed, correction route এবং change note দৃশ্যমান থাকবে। ${safety}</p>`;
    return {slug,title:titleFor(h1),description,label:topic,h1,searchTerms:keywords,intro:quick,body,priority};
  });
}
function faq(items){return `<h2>সাধারণ প্রশ্ন</h2><div class="faq-list">${items.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div>`;}
