const safety = `<div class="notice"><strong>Safety limits:</strong> These instructions are for your own or authorized router/network only. Do not provide any router password, Wi‑Fi password, MAC, serial or private network screenshot on Router Portal.</div>`;
const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugLink = (pageUrl, path, label) => `<a href="${pageUrl(path)}">${label}</a>`;
const titleFor = (h1) => {
  const t = `${h1} | Router Portal`;
  if (t.length <= 60) return t;
  const short = h1.split(':')[0].trim();
  const t2 = `${short} | Router Portal`;
  return t2.length <= 60 ? t2 : `${short.slice(0, 42).trim()} | Router Portal`;
};
const visual = (kind, label, nodes) => {
  const cls = kind === 'topology' ? 'topology-visual' : kind === 'compare' ? 'compare-visual' : kind === 'check' ? 'check-visual' : 'flow-visual';
  return `<figure class="router-visual ${cls}" role="img" aria-label="${esc(label)}"><div class="console-bar"><span class="console-dot"></span><span>${esc(label)}</span><code>ROUTER PORTAL / SAFE MODE</code></div><div class="visual-nodes">${nodes.map((n,i)=>`<div class="visual-node"><b>${i+1}</b><span>${esc(n)}</span></div>`).join('<i aria-hidden="true">→</i>')}</div><figcaption>${esc(label)} — original Router Portal visual; values are examples, not a guarantee for every model.</figcaption></figure>`;
};
const table = (rows) => `<div class="responsive-table"><table><thead><tr><th>what you see</th><th>It means</th><th>Safe next step</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div>`;
const specs = [
['/gateway/find-router-ip-windows-11/','Find router IP in Windows 11','find router IP Windows 11','In Command Prompt, run `ipconfig` and copy the Default Gateway for the active Wi‑Fi or Ethernet adapter.',['Open Command Prompt','Run ipconfig','Find Default Gateway','Open the address bar'],[['Adapter output','Gateways for Wi‑Fi and Ethernet may be different','Take the connection you are using'],['VPN output','VPN routes can be misleading','Check VPN/proxy temporarily'],['No gateway','Connection did not come or adapter inactive','Fix Wi‑Fi/Ethernet status']],'/find-router-ip/; /router-login/; /router-login-not-working/','flow','P0'],
['/gateway/find-router-ip-macos/','Find router IP on macOS','find router IP Mac','Read the Router field in Wi‑Fi Details, or run `route get default` in Terminal to view the current gateway.',['Open System Settings','Choose connected network','Read Router value','Open local address'],[['Settings path','The label changes according to the macOS version','Match the router field or route output'],['Ethernet','As with Wi‑Fi, there may be a different interface','Select active interface'],['No value','Network not connected','Reconnect before troubleshooting']],'/find-router-ip/; /router-login/; /gateway/router-login-by-hostname/','flow','P0'],
['/gateway/find-router-ip-android/','Finding default gateway in Android','find router IP Android','Check the Gateway or Router value in the Details/Advanced section of Connected Wi‑Fi.',['Open Wi‑Fi settings','Tap connected network','Read Gateway/Router','Copy without sharing'],[['OEM labels','Pixel/Samsung/other UI is different','Note the version-specific label'],['Mobile data','Cellular data does not show home gateway','Connect to home Wi‑Fi'],['Third-party app','Not always necessary','Use built-in details first']],'/find-router-ip/; /router-login/; /router-login-not-working/','flow','P0'],
['/gateway/find-router-ip-iphone-ipad/','Find router address on iPhone/iPad','find router IP iPhone','Copy the Router field in the info panel of Settings → Wi‑Fi → connected network.',['Open Settings','Tap Wi‑Fi','Tap connected network','Read Router field'],[['Cellular-only','Cellular data does not have a local gateway','Use the same Wi‑Fi network'],['Private Relay','This is not the router login address','Use the local Router field'],['iPad','Same concept as iPhone','Match OS label by version']],'/find-router-ip/; /router-login/; /router-login-not-working/','flow','P0'],
['/gateway/find-router-ip-linux/','Finding the default gateway in Linux','find router IP Linux','In Terminal `ip route` continue `default via`Identify the address of',['Open Terminal','Run ip route','Read default via','Open browser address bar'],[['Modern command','`ip route` Shows current route','Use this instead of the old command'],['NetworkManager','`nmcli device show` helpful','Get the gateway of the active device'],['No route','No network connection','Reconnect the interface']],'/find-router-ip/; /router-login/; /gateway/192-168-vs-10-private-ip/','flow','P0'],
['/gateway/192-168-vs-10-private-ip/','192.168.x.x vs 10.x.x.x private IP','192.168 vs 10 private IP','Both are private range; Your device’s current Default Gateway is the correct proof for router login.',['Identify private range','Read current gateway','Avoid public-IP confusion','Open local admin page'],[['192.168.0.0/16','Very common on home LANs','The model is not inferred by address alone'],['10.0.0.0/8','Also seen in ISP/gateway','10.0.0.1 is not universal'],['100.64.0.0/10','Can be CGNAT context','See WAN/public distinction']],'/find-router-ip/; /tools/what-is-my-ip/; /network/cgnat-explained/','compare','P0'],
['/gateway/router-login-by-hostname/','Login with router hostname','router login by hostname','Instead of some model IP `routerlogin.net`, `tplinkwifi.net` or using local hostname; Compare with official source.',['Read model label','Find documented hostname','Stay on local network','Verify certificate/URL'],[['Hostname','Model-specific local name','Match the manual/support page'],['DNS failure','Hostname may not resolve','Use the current gateway'],['Public lookalike','Internet site not local admin','Check address bar and local connection']],'/router-model-login/; /find-router-ip/; /models/router-manuals-and-support/','flow','P1'],
['/gateway/ipv6-router-login/','Opening the router admin page with IPv6','IPv6 router login','Using an IPv6 gateway or link-local address may require interface zone and exact model documentation.',['Check IPv6 gateway','Confirm local link','Use documented bracket syntax','Verify router page'],[['Link-local','`fe80::` interface-specific','zone identifier may be required'],['IPv6 disabled','Not all routers operate the same way','Take IPv4 gateway fallback'],['Admin exposure','WAN IPv6 access is a different matter','Do not enable remote management']],'/find-router-ip/; /network/ipv6-home-router-basics/; /security/remote-management-risk/','topology','P1'],
['/models/how-to-identify-router-model/','Identify router model and hardware revision','identify router model','Create exact device record by matching label’s model code, hardware revision and ISP branding.',['Photograph label privately','Read model code','Read hardware revision','Check official support'],[['Model code','Not marketing family, exact code','Get exact match on support page'],['Revision','A1/V2/Ver.3 instruction may change','Guide is not applicable except for revision'],['ISP label','Could be provider firmware','Keep the ISP support path separate']],'/router-model-login/; /models/hardware-revision/; /models/router-manuals-and-support/','check','P0'],
['/models/hardware-revision/','Hardware revision why login instructions change','router hardware revision','Firmware, menu, reset and default state may be different in revision of the same product name.',['Locate revision','Match manual','Check firmware family','Use exact steps'],[['Revision label','V1/V2/A1 fields are important','Place it on the model page'],['Firmware','ISP build may vary','Check out the official update notes'],['Reset hole','timing model-specific','Avoid random timing']],'/models/how-to-identify-router-model/; /models/firmware-isp-variants/; /factory-reset-router/','compare','P0'],
['/models/router-login-evidence-card/','How to read Verified router evidence card','router login evidence card','View model, revision, login address, credential status, source and last-checked date together on an evidence card.',['Match exact model','Read credential status','Open source','Check date'],[['Address','Possible local URL','Confirm with current gateway'],['Credential status','factory/label/setup/unknown','Do not assume universal password'],['Source/date','evidence freshness','Recheck if firmware changes']],'/router-model-login/; /default-router-passwords/; /models/router-manuals-and-support/','check','P0'],
['/isp/router-login-by-isp/','Router login preparation according to ISP','router login by ISP','In ISP-provided gateways, admin access, app control, bridge mode and support boundary vary by provider.',['Identify provider','Identify supplied device','Check app/manual','Protect account'],[['Provider firmware','Generic brand steps may not match','See ISP guide first'],['Managed access','Admin UI may be closed','Use support/official app'],['Own router','ISP modem/router is separate','Write down the topology']],'/isp/isp-router-admin-access/; /models/firmware-isp-variants/; /gateway/find-router-ip-windows-11/','topology','P0'],
['/isp/isp-router-admin-access/','ISP router vs own router admin access','ISP router admin access','Decide which device to log in by understanding the ISP gateway, bridge modem and the boundary of your router.',['Draw topology','Find each gateway','Check provider policy','Choose safe admin path'],[['Single gateway','A router controls','Open the current gateway'],['Modem + router','Can be double NAT','Distinguish upstream/downstream'],['Managed device','credentials provider-controlled','Take provider path, not reset']],'/network/double-nat-diagnosis/; /network/bridge-mode-vs-ap-mode/; /isp/router-login-by-isp/','topology','P0'],
['/models/firmware-isp-variants/','Firmware and ISP variant login differences','router firmware ISP variant','Menu, hostname, credentials and update policy may be different in retail and ISP firmware of the same model.',['Read firmware label','Match region/ISP','Open release notes','Choose correct manual'],[['Retail firmware','manufacturer menu','Match official support'],['ISP firmware','custom UI/access','provider support priority'],['Region','Can change channel/power/menu','Get region-specific sources']],'/models/hardware-revision/; /security/firmware-update-safety/; /isp/router-login-by-isp/','compare','P0'],
['/models/router-manuals-and-support/','Looking for router manual and official support','router manual support','Find manufacturer/ISP official manual, firmware and support page with exact model and revision.',['Read exact model','Open official domain','Check revision','Save source date'],[['Manual','PDF or web guide','Put the copyright/URL'],['Firmware','Release note is important','wrong region not flash'],['Support','The ISP case is different','Do official escalation']],'/models/how-to-identify-router-model/; /models/firmware-isp-variants/; /editorial-policy/','check','P0'],
['/brand-router-model-search/','Brand/model search and verified index','router brand model search','Use Brand → model → revision → source flow; Do not index empty or unsupported results.',['Choose brand','Search exact model','Read evidence status','Open source'],[['Brand page','Discovery hub only','No credential without model proof'],['No result','unsupported state','Not the thin doorway page'],['Verified result','with source/date','Open the related task']],'/router-model-login/; /default-router-passwords/; /models/router-login-evidence-card/','flow','P0'],
['/security/after-router-login-checklist/','Router security checklist after login','router security checklist','After login, review admin password, firmware, remote management, UPnP, Wi‑Fi and backup.',['Change admin credential','Update firmware','Review remote access','Backup safely'],[['Admin','unique passphrase','private password manager'],['Remote access','attack surface','off if not needed'],['Backup','settings recovery','Credential export is not']],'/change-router-admin-password/; /security/firmware-update-safety/; /security/remote-management-risk/','check','P0'],
['/security/router-admin-account-types/','Router admin account and credential states','router admin account types','Understand factory default, label-generated, setup-created, ISP-managed and unknown state separately.',['Identify account state','Check model/revision','Avoid guessing','Create safe credential'],[['Factory','documented starting value','Change to first login'],['Label-generated','unit-specific','label privately read'],['ISP-managed','provider controlled','official support']],'/default-router-passwords/; /change-router-admin-password/; /isp/isp-router-admin-access/','compare','P0'],
['/security/firmware-update-safety/','Router firmware update done safely','safe router firmware update','Do not update firmware without checking backup, exact revision/region, power stability and official release note.',['Read release notes','Backup configuration','Match revision/region','Update and verify'],[['Wrong image','Router may be unusable','exact support page match'],['Power loss','Update may be corrupt','Use stable power'],['After update','Can change settings/menu','login/Wi‑Fi verify']],'/models/firmware-isp-variants/; /models/router-manuals-and-support/; /security/firmware-end-of-life/','check','P0'],
['/security/firmware-end-of-life/','Router firmware end-of-life and replacement','router firmware end of life','If security updates are stopped, consider exposure, support, ISP compatibility and replacement cost together.',['Check last update','Check vendor notice','Assess exposure','Plan replacement'],[['EOL','No new patch','Remote features closure/replacement'],['Unsupported ISP','Check provider before replacement','Think bridge/AP option'],['Old hardware','Not performance, security risk','data-backed decision']],'/security/firmware-update-safety/; /reviews/router-for-apartment/; /reviews/router-for-home-server/','compare','P1'],
['/security/remote-management-risk/','Risks of remote router administration','router remote management risk','Keep WAN-side admin access off if not needed; Understand the difference between local admin and secure VPN/relay.',['Find remote admin setting','Check allowed source','Disable if unnecessary','Verify locally'],[['WAN admin','Internet-facing login','off or restricted'],['Cloud app','vendor account path','MFA/privacy review'],['VPN','safer remote route','official method follow']],'/security/after-router-login-checklist/; /network/dmz-vs-port-forwarding/; /security/router-firewall-basics/','topology','P0'],
['/security/upnp-explained/','UPnP key and review safely','UPnP router security','Review according to device need by understanding the benefits/risks of UPnP convenience and automatic port mapping.',['List dependent devices','Inspect mappings','Choose policy','Recheck apps'],[['Automatic mapping','Manual work is less','unexpected exposure review'],['IoT','Trust boundary may be weak','Think segmentation'],['Disable','Some apps may break','specific alternative test']],'/port-forwarding/; /security/guest-network-vs-iot-network/; /security/after-router-login-checklist/','compare','P1'],
['/security/wps-security/','WPS security and the decision to turn it off','WPS security router','Understand push-button/PIN behavior, convenience and risk model of WPS and disable as needed.',['Identify WPS mode','Check client needs','Disable PIN if possible','Verify Wi‑Fi'],[['PIN','Weaker path in many cases','disable/review'],['Push button','short pairing window','Keep physical control'],['Legacy client','compatibility issue','newer secure setup']],'/security/after-router-login-checklist/; /wifi/wpa2-vs-wpa3/; /wifi/wifi-password-sharing-safely/','compare','P1'],
['/security/guest-network-vs-iot-network/','Guest network vs IoT network','guest network vs IoT','Guest isolation and IoT segmentation are not the same thing; Make policy according to router feature and device trust.',['Inventory devices','Enable guest isolation','Separate IoT','Test local access'],[['Guest','visitor internet access','LAN isolation check'],['IoT','untrusted device group','dedicated SSID/VLAN'],['Printer/NAS','local access need','exception document']],'/security/router-firewall-basics/; /wifi/wpa2-vs-wpa3/; /network/bridge-mode-vs-ap-mode/','topology','P1'],
['/security/router-firewall-basics/','Router firewall basics and verification','router firewall basics','Review the interaction of inbound rules, IPv6 policy and port forwarding whether firewall is enabled or not.',['Check firewall state','Review inbound rules','Review IPv6','Test approved service'],[['Default firewall','stateful filtering','Keeping the default is helpful'],['Inbound rule','specific exposure','least privilege'],['IPv6','There may be a separate policy','IPv6 firewall verify']],'/security/remote-management-risk/; /network/ipv6-home-router-basics/; /port-forwarding/','check','P1'],
['/security/hacked-router-triage/','Triage if router compromise is suspected','hacked router what to do','If you see unusual DNS, unknown admin change or redirect, preserve evidence, isolate and take official recovery path.',['Record symptoms','Disconnect risky access','Change credentials safely','Check firmware/ISP'],[['DNS redirect','resolver setting inspect','device/browser also check'],['Unknown admin','account state review','provider/vendor escalate'],['Evidence','Reset can lose','Keep notes, not secret']],'/security/after-router-login-checklist/; /security/firmware-update-safety/; /network/dns-settings-router/','check','P1'],
['/wifi/slow-wifi-diagnosis/','Slow Wi-Fi diagnosis: layered flow','slow Wi-Fi diagnosis','Check Wired vs Wi‑Fi, gateway latency, distance, interference, client load and ISP speed separately.',['Test wired baseline','Test near router','Test far room','Compare time/load'],[['Wired fast','wireless layer issue','channel/placement review'],['Both slow','WAN/ISP or router load','public test caveat'],['One device','client issue','driver/power settings']],'/tools/ping-test/; /wifi/channel-interference/; /wifi/bufferbloat-and-latency/','flow','P0'],
['/wifi/frequent-disconnects/','What to check if Wi-Fi keeps disconnecting?','Wi-Fi disconnect troubleshooting','Check SSID band steering, signal, power saving, firmware, DHCP lease and interference in order.',['Observe pattern','Check signal/band','Update client/router','Review DHCP'],[['All devices','router/AP issue','logs/firmware check'],['One device','client issue','forget/rejoin/update'],['Only one band','channel/compatibility','band setting compare']],'/wifi/slow-wifi-diagnosis/; /security/firmware-update-safety/; /network/dhcp-reservation-vs-static-ip/','flow','P0'],
['/wifi/channel-interference/','Wi-Fi channel and interference selection','best Wi-Fi channel','Choose channel by looking at 2.4GHz channel overlap, 5GHz DFS/region behavior and apartment interference.',['Identify crowded band','Check channel width','Choose allowed channel','Retest latency'],[['2.4GHz','more overlap','20MHz often safer'],['5GHz','DFS/region caveat','device support check'],['Width','wider is not always faster','stability first']],'/wifi/2-4ghz-vs-5ghz-vs-6ghz/; /wifi/slow-wifi-diagnosis/; /reviews/router-for-apartment/','compare','P1'],
['/wifi/2-4ghz-vs-5ghz-vs-6ghz/','2.4GHz vs 5GHz vs 6GHz','2.4 5 6 GHz Wi-Fi','Band choice range, interference, device support, channel width and trade-off of backhaul.',['List client support','Map room distance','Choose band policy','Retest'],[['2.4GHz','range/wall penetration','lower throughput'],['5GHz','capacity/latency','shorter range'],['6GHz','newer clients','region/device support']],'/wifi/channel-interference/; /wifi/wpa2-vs-wpa3/; /reviews/wifi-extenders-and-mesh/','compare','P0'],
['/wifi/wpa2-vs-wpa3/','WPA2 vs. WPA3: No Wi-Fi security','WPA2 vs WPA3','Consider WPA3 security benefit, client compatibility, transition mode and password hygiene together.',['Check client support','Choose mode','Set strong key','Reconnect devices'],[['WPA3','newer protection','client support required'],['WPA2','legacy compatibility','AES preferred'],['Transition','mixed clients','Keep the upgrade plan']],'/security/wps-security/; /wifi/wifi-password-sharing-safely/; /security/after-router-login-checklist/','compare','P0'],
['/wifi/ssid-change-checklist/','Checklist before and after changing SSID','change Wi-Fi SSID','Plan the impact of devices, IoT, mesh nodes and saved networks before SSID change.',['Record current setup','Choose neutral SSID','Save settings','Reconnect clients'],[['SSID name','Network identity changes','Not personal info'],['Mesh','Nodes need sync','same controller path'],['IoT','reconnect cost','Do the inventory first']],'/change-wifi-password/; /wifi/wifi-password-sharing-safely/; /wifi/wpa2-vs-wpa3/','check','P1'],
['/wifi/wifi-password-sharing-safely/','Share Wi-Fi password/QR securely','share Wi-Fi password safely','QR and password bearer credential; Consider guest network, expiry/rotation and private sharing.',['Choose guest or main','Generate locally','Share privately','Rotate when needed'],[['QR','Access only if there is an image','Not a public post'],['Guest','LAN isolation','IoT/NAS access test'],['Rotation','old shares expire','devices reconnect']],'/tools/wifi-qr-code/; /security/guest-network-vs-iot-network/; /change-wifi-password/','check','P1'],
['/wifi/bufferbloat-and-latency/','Bufferbloat and gaming latency','bufferbloat gaming latency','Queue delay, upload saturation, QoS/SQM and wired baseline can be more important than bandwidth speed.',['Measure idle latency','Load upload/download','Compare queue delay','Tune QoS/SQM'],[['Idle ping','baseline','gateway vs internet compare'],['Loaded ping','queue growth','upload cap/SQM'],['Gaming client','Wi‑Fi variability','wired/control test']],'/tools/ping-test/; /wifi/slow-wifi-diagnosis/; /reviews/best-wifi-routers-for-gaming/','compare','P1'],
['/network/dhcp-reservation-vs-static-ip/','DHCP reservation vs static IP','DHCP reservation vs static IP','Router-managed reservation usually keeps the device address stable; Understand the trade-off of manual static config.',['Identify device','Record MAC privately','Reserve address','Reconnect and verify'],[['Reservation','router assigns fixed lease','LAN conflict is less'],['Static IP','device-side setting','gateway/DNS mismatch risk'],['Server','Stable target is required','document rollback']],'/port-forwarding/; /tools/port-forwarding-worksheet/; /network/double-nat-diagnosis/','compare','P0'],
['/network/dns-settings-router/','Router DNS settings: choice and troubleshooting','router DNS settings','Understand ISP behavior, DoH/DoT, IPv6 DNS, fallback and privacy effect before DNS resolver change.',['Record current DNS','Choose documented resolver','Apply carefully','Test resolution'],[['ISP DNS','support/integration','default may be valid'],['Public DNS','alternative resolver','privacy/latency varies'],['IPv6 DNS','separate path','both stacks test']],'/tools/dns-leak-router-check/; /security/hacked-router-triage/; /network/ipv6-home-router-basics/','check','P0'],
['/network/bridge-mode-vs-ap-mode/','Bridge mode vs access point mode','bridge mode vs access point','Bridge turns off modem routing; AP mode changes the secondary router’s Wi‑Fi/LAN role—draw the topology first.',['Draw current topology','Identify routing device','Choose bridge or AP','Verify gateway'],[['Bridge','upstream router routes','ISP support may matter'],['AP','main router still routes','DHCP off/managed'],['Double NAT','two routers route','mode change can fix']],'/isp/isp-router-admin-access/; /network/double-nat-diagnosis/; /network/repeater-vs-access-point/','topology','P0'],
['/network/repeater-vs-access-point/','Difference between repeater, mesh and access point','repeater vs access point','Select extender/repeater/AP/mesh by looking at backhaul, latency, roaming, Ethernet availability and placement.',['Check Ethernet','Map coverage','Choose backhaul','Retest room'],[['Repeater','wireless backhaul','capacity/latency cost'],['AP','wired backhaul','stable and predictable'],['Mesh','roaming/controller','node placement matters']],'/reviews/wifi-extenders-and-mesh/; /wifi/slow-wifi-diagnosis/; /wifi/channel-interference/','compare','P1'],
['/network/double-nat-diagnosis/','Detecting and fixing Double NAT','double NAT diagnosis','Routing two routers can complicate inbound access, gaming, discovery and port forwarding.',['Compare WAN/LAN ranges','Trace gateway chain','Choose bridge/AP','Retest service'],[['Two private ranges','possible double NAT','upstream/downstream map'],['ISP gateway','managed device','bridge/AP policy check'],['Port failure','not always double NAT','CGNAT also test']],'/isp/isp-router-admin-access/; /network/bridge-mode-vs-ap-mode/; /network/cgnat-explained/','topology','P0'],
['/network/cgnat-explained/','What is CGNAT and why does port forwarding fail?','CGNAT port forwarding','Inbound forwarding may not work if WAN address is private/shared; Understand ISP/IPv6/relay alternatives.',['Compare router WAN','Compare public IP','Check ISP terms','Choose alternative'],[['Private WAN','CGNAT likely','ISP request/public option'],['Shared public IP','inbound blocked','relay/VPN alternative'],['IPv6','different exposure model','firewall first']],'/port-forwarding/; /network/ipv6-home-router-basics/; /tools/local-vs-public-ip-check/','topology','P0'],
['/network/ipv6-home-router-basics/','IPv6 basics on home routers','IPv6 home router','IPv6 address, prefix delegation, firewall, SLAAC/DHCPv6 and router admin access are separate issues.',['Check ISP IPv6','Read prefix','Review firewall','Test client'],[['Global address','may be internet-routable','inbound firewall verify'],['ULA','private-like local range','not public reachability'],['Prefix delegation','ISP changes prefix','avoid hard-coded rules']],'/gateway/ipv6-router-login/; /security/router-firewall-basics/; /network/cgnat-explained/','topology','P1'],
['/network/mtu-mss-home-network/','MTU and MSS: home-network troubleshooting','MTU MSS troubleshooting','Isolate packet-size issues by understanding the relationship between fragmentation, VPN/PPPoE path and MSS clamping.',['Observe symptom','Test path','Check WAN type','Change only documented setting'],[['MTU','maximum frame payload','path-specific value'],['MSS','TCP segment hint','TCP-only context'],['VPN/PPPoE','overhead added','provider documentation']],'/network/dns-settings-router/; /wifi/slow-wifi-diagnosis/; /gateway/ipv6-router-login/','compare','P1'],
['/network/port-forwarding-vs-port-triggering/','Port forwarding vs. port triggering','port forwarding vs triggering','Understand which use-cases static inbound mapping and outbound-triggered temporary mapping fit into.',['Identify service','Check vendor docs','Choose mapping','Test and cleanup'],[['Forwarding','always mapped','exposure remains'],['Triggering','outbound event opens','support varies'],['No mapping','relay/outbound app','safer when supported']],'/port-forwarding/; /tools/port-forwarding-worksheet/; /network/cgnat-explained/','compare','P1'],
['/network/dmz-vs-port-forwarding/','DMZ host vs. specific port forwarding','DMZ vs port forwarding','DMZ broadly exposes a host; Least-privilege specific forwarding is usually the safer starting point.',['Identify requirement','Check service ports','Use specific rule','Remove after use'],[['DMZ','broad exposure','avoid as default'],['Specific port','narrow exposure','service documentation'],['CGNAT','DMZ cannot bypass','check WAN path']],'/port-forwarding/; /security/router-firewall-basics/; /tools/port-forwarding-worksheet/','compare','P0'],
['/tools/gateway-self-check/','Gateway self-check worksheet','default gateway checker','Fill out the safe local-access worksheet by writing device, interface, gateway, browser result and next action.',['Record interface','Record gateway','Open address','Record result'],[['Interface','Wi‑Fi/Ethernet/VPN','Select the active path'],['Gateway','local next hop','Not public IP'],['Result','login/timeout/refused','Take the next branch']],'/find-router-ip/; /router-login-not-working/; /gateway/192-168-vs-10-private-ip/','check','P0'],
['/tools/local-vs-public-ip-check/','Local IP vs public IP comparison tool','local IP vs public IP','Local/private address, router WAN and observed public IP are not the same; Mismatch can be normal in CGNAT.',['Read local address','Read gateway','Observe public IP','Compare cautiously'],[['Local IP','LAN device identity','not internet-facing'],['Gateway','router next hop','can be admin path'],['Public IP','ISP/VPN-facing','sensitive context']],'/tools/what-is-my-ip/; /find-router-ip/; /network/cgnat-explained/','compare','P0'],
['/tools/dns-leak-router-check/','Router DNS leak self-check','router DNS leak check','Compare expected resolver and observed DNS path; If you don’t test VPN/DoH/IPv6 separately, the result is incomplete.',['Choose expected resolver','Run controlled test','Compare IPv4/IPv6','Interpret limits'],[['Resolver','query endpoint','ownership/geolocation uncertain'],['VPN','path may intentionally differ','VPN policy read'],['DoH','browser bypass','Not a router-only conclusion']],'/network/dns-settings-router/; /security/after-router-login-checklist/; /network/ipv6-home-router-basics/','topology','P2'],
['/tools/port-forwarding-worksheet/','Port-forwarding rule worksheet','port forwarding worksheet','Enter service, listener, reserved LAN IP, protocol, source restriction, test method and cleanup date.',['Name service','Reserve host','Set least privilege','Test and cleanup'],[['Listener','service actually running','host firewall check'],['Rule','TCP/UDP/ports','vendor docs match'],['Cleanup','temporary exposure','disable/delete date']],'/port-forwarding/; /network/dhcp-reservation-vs-static-ip/; /network/cgnat-explained/','check','P0'],
['/reviews/router-for-apartment/','Choosing a router for a small apartment','best router for apartment','Measure floor area, wall density, ISP speed, client mix and Ethernet availability beforehand; Use evidence tables, not "best" claims.',['Map apartment','Count clients','Check ISP speed','Compare tested evidence'],[['Coverage','walls/placement matter','floor-plan test'],['Band','interference varies','2.4/5/6 support'],['Mesh','not always needed','wired AP alternative']],'/wifi/2-4ghz-vs-5ghz-vs-6ghz/; /network/repeater-vs-access-point/; /wifi/slow-wifi-diagnosis/','compare','P1'],
['/reviews/router-for-home-server/','Router selection for home server/NAS','best router for home server','See Stable DHCP reservations, firewall/IPv6 policy, backup and remote-access alternatives; Not just port count.',['Define service','Assess exposure','Check CGNAT/IPv6','Compare firmware support'],[['NAS','local access first','backup and least privilege'],['Remote access','forwarding risk','VPN/relay alternative'],['Firmware','long support matters','last update date']],'/port-forwarding/; /network/dhcp-reservation-vs-static-ip/; /network/cgnat-explained/; /security/router-firewall-basics/','topology','P1']
];
export function makeFiftyPages(pageUrl){
  return specs.map((r)=>{
    const [slug,h1,primary,quick,steps,rows,related,visualKind,priority]=r;
    const relatedLinks=related.split(';').map(x=>{const [p,label]=x.trim().split('|'); return slugLink(pageUrl,p,label||p);}).join(' · ');
    const keywords=`${primary}, Router Portal, router guide, ${h1}`;
    const description=`${quick} with secure steps, restrictions, internal links and source-aware router guidance.`;
    const topic = h1.includes('security')||h1.includes('WPS')||h1.includes('UPnP')||h1.includes('firmware')||h1.includes('compromise')?'Security & maintenance':h1.includes('Wi-Fi')||h1.includes('GHz')||h1.includes('SSID')||h1.includes('WPA')||h1.includes('bufferbloat')?'Wi-Fi performance':h1.includes('router IP')||h1.includes('gateway')||h1.includes('hostname')||h1.includes('With IPv6')?'Gateway & local access':h1.includes('router model')||h1.includes('hardware')||h1.includes('ISP')||h1.includes('manual')||h1.includes('evidence')||h1.includes('Brand')?'Models, brands & ISP':h1.includes('election')?'Buying guide':h1.includes('tool')||h1.includes('worksheet')||h1.includes('IP Vs')||h1.includes('self-check')?'Tools & worksheets':'Network architecture';
    const faqItems=[
      [`Will the same rule in ${h1} work on all routers?`,`no Menu or result can change according to model, hardware revision, firmware, ISP, region and previous setup. Match exact source and current gateway.`],
      ['Can Router Portal see my credentials?','no This page will not ask for a router or Wi‑Fi password; The local admin page will only open in your own browser/network.'],
      ['What is the first next step if it does not work?','Check connection, current default gateway, model/revision and official manual together. Factory reset or broad exposure is not the first step.']
    ];
    const body=`${safety}<div class="admin-console"><div><span class="status-pill">${priority} · ${topic}</span><span class="status-pill muted">SOURCE-AWARE GUIDE</span></div><strong>ROUTER PORTAL / ${esc(primary).toUpperCase()}</strong><small>Compare model, revision, ISP and firmware scope first</small></div><div class="answer-lead"><strong>Original answer above:</strong> ${quick}</div>${visual(visualKind,`${h1} safe workflow`,steps)}<h2>Why is this page useful?</h2><p>A common mistake in ${quick} ${h1} queries is to assume the popular address or password is universal. In this guide, decision point, evidence status and stop condition are kept separately so that the same information does not appear again and again for no reason.</p><h2>Work step</h2><ol>${steps.map(s=>`<li>${s}</li>`).join('')}</ol><h2>Router-admin style decision panel</h2>${table(rows)}<h2>Verification and limitations</h2><p>Check the exact model/revision, firmware/ISP scope, official manual or standards source and last-reviewed date before publishing the result or instruction. If unknown <strong>not verified</strong> write; Don’t present guesses as verified credentials or guaranteed fixes.</p><h2>Next useful links</h2><p>${relatedLinks}</p>${faq(faqItems)}<h2>Source and review note</h2><p>This page should use sources such as manufacturer/ISP documentation, IETF/IANA/CISA or relevant OS documentation. Author, Reviewer, Last reviewed, correction route and change note will be visible on the page. ${safety}</p>`;
    return {slug,title:titleFor(h1),description,label:topic,h1,searchTerms:keywords,intro:quick,body,priority};
  });
}
function faq(items){return `<h2>General questions</h2><div class="faq-list">${items.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div>`;}
